### PR TITLE
Update winetricks

### PR DESCRIPTION
**Pull request by vanillajonathan**
Proper capitalization of acronyms (such as GUI, URL, DLL and SP).
End sentences with a period.
Fix names of software titles where incorrect.
Capitalized software titles and brand names (such as Windows and Steam).
Adjust comments to not exceed 80 characters.

### CODE REVIEW

**Comment by Chiitoo** [comment]
This is a bit late comment (would have been better for 'Update winetricks #638'), but shouldn't 'AutoHotKey' have been 'AutoHotkey'?  ^^

By the by, I for one would appreciate at least a bit more descriptive titles (“Update winetricks” doesn't tell much).

Thanks!

**Comment by qwertychouskie** [comment]
"the POSIX stanard"?

**Comment by vanillajonathan** [comment]
@Chiitoo, you're right it should be AutoHotkey, not AutoHotKey.

@qwertychouskie, thanks for spotting that regression where a typo was introduced.

**Comment by austin987** [comment]
As others have said, the changelog entry needs to be updated. You really need to use a real git client for changes like this (and again, squash them).

Aside from that, some of these changes were rejected before (e.g., Xvid), and others are unneeded. Primarily, your use of periods is completely inconsistent (e.g., in the first few lines, you add a period to the first, but not the next 3 lines). Not every comment needs a period to end it, especially bullet points

Some others are undesirable, e.g., sha1sum is a known technical term, there's no need to obfuscate it for a more formal sentence that is a code comment (and that no longer matches the function name).

**Comment by vanillajonathan** [comment]
Well you could just merge commit 367c34cab948da7a02eb6421909760160d98739f then.

**Comment by austin987** [comment]
The Github gui merge doesn't allow that, as they're intermingled in one PR.

**Pull request closed without merging**
