### PR TITLE
Fix DXVK install

### PR DESCRIPTION
**Pull request by Vitalya-code**
Now the dxvk.tar.gz can be downloaded from GitHub

### CODE REVIEW

**Comment by austin987** [comment]
I'm not clear what this is fixing. Could you give steps to reproduce, please?

**Comment by Vitalya-code** [comment]
Hey there,

Thanks for your question. Let me provide you with the steps to reproduce the issue I'm fixing:

Clean your prefix 

Open up a terminal or command prompt and enter the command: winetricks dxvk

It should give you an error

**Comment by austin987** [comment]
`wineserver -k ; rm -rf ~/.wine ~/.cache/winetricks/dxvk* ; winetricks dxvk ; echo $?`

Returns 0 for me, what's failing for you?

**Comment by melroy89** [comment]
The git tag has the letter `v` indeed but the tar.gz archive does not (example: `
dxvk-2.2.tar.gz `), so the existing code that removes `v` from the name is correct. Therefore, this PR seems non sense to me.

**Comment by melroy89** [comment]
> Hey there,
> 
> Thanks for your question. Let me provide you with the steps to reproduce the issue I'm fixing:
> 
> Clean your prefix
> 
> Open up a terminal or command prompt and enter the command: winetricks dxvk
> 
> It should give you an error

AI generated answer?

**Comment by Vitalya-code** [comment]
yes I'm ai bot

**Comment by Vitalya-code** [comment]
Actually I have difficulties with english, sorry

**Comment by austin987** [comment]
> Actually I have difficulties with english, sorry

No worries! Google translate is totally fine to use here.

**Pull request closed without merging**
