### PR TITLE
remove_mono: fix verb for Wine 4.6(+)

### PR DESCRIPTION
**Pull request by bobwya**
* fixes: https://github.com/Winetricks/winetricks/issues/1290
 * fixes: https://github.com/Winetricks/winetricks/issues/1291

### CODE REVIEW

**Comment by bobwya** [comment]
@austin987 

The new packaging installs the new variant:
 * **Wine Mono Windows Support**

The old packaging installs the old variant:
 * **Wine Mono**

There isn't 2 packages install for a single **wine-mono** version. It's an either/ or situation.

Bob

**Comment by austin987** [comment]
It would be a lot simpler to just remove the `grep -v` bit; i.e.,:

```
diff --git a/src/winetricks b/src/winetricks
index 4caa83e..ee4418b 100755
--- a/src/winetricks
+++ b/src/winetricks
@@ -21095,7 +21095,7 @@ w_metadata remove_mono settings \
 load_remove_mono()
 {
     # wine-4.6 comes with two installers, removing "Wine Mono Runtime" will also remove "Wine Mono Windows Support"
-    mono_uuid="$("${WINE_ARCH}" uninstaller --list | grep 'Wine Mono' | grep -v 'Wine Mono Windows Support' | cut -f1 -d\|)"
+    mono_uuid="$("${WINE_ARCH}" uninstaller --list | grep 'Wine Mono' | cut -f1 -d\|)"
     if test "$mono_uuid"; then
         for uuid in $mono_uuid;
            do "${WINE_ARCH}" uninstaller --remove "$uuid"
```

**Comment by austin987** [comment]
Though it's curious why this doesn't work as is, it does for me. Mono installs two MSIs:
```
austin@laptop ~ $ wine uninstaller --list
{BB9BDB97-C247-4F20-B710-8B6765F67105}|||Wine Gecko (32-bit)
{95E1A5A7-9C47-5B8F-94C7-03C26A544072}|||Wine Mono Runtime
{C1E530E6-B87C-5982-8173-5417B92E5F56}|||Wine Mono Windows Support

austin@laptop ~ $ wine --version
wine-4.14
```

The current script ignores the windows support uuid, so only Wine Mono Runtime is uninstalled. Interestingly, uninstaller prints a warning about the second uuid:
`uninstaller: The application with GUID '{C1E530E6-B87C-5982-8173-5417B92E5F56}' was not found`

In any case, at the end, no mono is installed:
```
austin@laptop ~ $ wine uninstaller --list
{BB9BDB97-C247-4F20-B710-8B6765F67105}|||Wine Gecko (32-bit)
```

**Comment by bobwya** [comment]
Hmm, interesting. When I unpack the newer **wine-mono 4.9.2** binary from: [wine-mono-bin-4.9.2.tar.gz](http://dl.winehq.org/wine/wine-mono/4.9.2/wine-mono-bin-4.9.2.tar.gz)
under: 

    /usr/share/wine/mono/wine-mono-4.9.2/

Then when I boot a clean **32-bit WINEPREFIX**, I get:

    WINEDEBUG=-all wine uninstaller --list
    {BB9BDB97-C247-4F20-B710-8B6765F67105}|||Wine Gecko (32-bit)
    {C1E530E6-B87C-5982-8173-5417B92E5F56}|||Wine Mono Windows Support

    wine --version
    wine-4.14

I tested manually running the **msi** installer at:

    cd /usr/share/wine/mono/wine-mono-4.9.2/support/
    wine msiexec /i winemono-support.msi

with the same result. Obviously I uninstalled any pre-existing wine-mono packages, installed in the test WINEPREFIX.

This appears to match up with other folks using the newer wine-mono packaging...
So I'm not seeing the second package. What steps are you using to install the new wine-mono package?

**Comment by austin987** [comment]
@bobwya I'm not using a prepacked version; I'm building/installing Wine with:
`./configure && make -j$(nproc) && sudo make install`

so the binaries are in /usr/local. When I run `wineboot`, I'm prompted to download the installers, which then end up in ~/.cache/wine.

I looked into it, it seems this behavior was introduced in wine-mono-4.8.1 (wine wine-4.6). Looks like this is intended, a shared install will only have 'Wine Mono Windows Support', while the msi installer will also install 'Wine Mono Runtime'. See https://github.com/madewokherd/wine-mono/releases/tag/wine-mono-4.8.1

I've committed my fix here: https://github.com/Winetricks/winetricks/commit/710c154225358e10964968ddbae7dd9679f8cb2f

I appreciate your attempt, but I think this approach is simpler and more future proof (at least until uninstaller fails for unknown installers).

**Pull request closed without merging**
