### PR TITLE
faudio: new verb

### PR DESCRIPTION
**Pull request by austin987**
For #1162.

Needs testing, but I don't have things set up to game, so hoped y'all could ;)

@tgurr @aeikum @Gcenx (and fyi @Kron4ek)

### CODE REVIEW

**Comment by Kron4ek** [comment]
Tested, it works properly.

I also added STABLE file into repo, you can use it in the verb. Now there are two:

LATEST - contain latest available build version (including git builds)
STABLE - contain latest avaiable stable build version (19.01 for now)

Also to note, it's ok that libgcc_s_sjlj-1.dll is missing in 64-bit build, it required only for 32-bit builds.

**Comment by aeikum** [comment]
Looks fine to me, too.

**Comment by bobwya** [comment]
The verb works OK for me too...

@aeikum 

Somewhat OT... I was kind of hoping that using **faudio** would help with the scratchy audio in Fallout 4... However it looks like I still need to use PULSE_LATENCY_MSEC though, for that issue... Yeah??

**Comment by aeikum** [comment]
@bobwya That's a complicated question and definitely OT. Are you using the winepulse patches from wine-staging? They hopefully address that kind of problem (i.e. you should *not* have to use that environment variable if you are using those patches). If they don't fix it for you, let's move this discussion to wine bug 45623.

**Comment by bobwya** [comment]
@aeikum Yeah sorry, a "slight sideways" issue hijack! I've tried both Proton 3.16-5 and Wine Staging 4.0 (with this winetricks verb). I do want to see if a high CPU load is trigging this issue... I'll report back on wine bug 45623.

I guess I thought **faudio** would be the "magic bullet" for all audio ills... :-)

**Comment by Gcenx** [comment]
It’s also working fine for me also

**Comment by austin987** [comment]
Fixed by https://github.com/Winetricks/winetricks/commit/6843ab37c458953bb55371381b518fa326144dde

**Pull request closed without merging**
