### PR TITLE
winetricks: Attempt to improve compactness

### PR DESCRIPTION
**Pull request by Kreyren**
This shrinks whole script by 663 lines without any negative effect

Signed-off-by: Jacob Hrbek <werifgx@gmail.com>

### CODE REVIEW

**Comment by Chiitoo** [comment]
I dislike this change greatly, as it makes things less readable.  It's not like I'm even contributing to the code though, so... just throwing the opinion out there.  :]

**Comment by Kreyren** [comment]
> I dislike this change greatly, as it makes things less readable. It's not like I'm even contributing to the code though, so... just throwing the opinion out there. :]

```bash
# Proposed
function() {
  return 0
}
```

Compared to

```bash
# Current
function() 
{
  return 0
}
```

From my point of view:

proposed makes is more readable since there are no unnecessary spaces -> you can fit more code in one screen.

Or what is your argument?

**Comment by Chiitoo** [comment]
I simply find code more readable when the opening and closing braces are aligned (similarly to what is often referred to as the "Allman style" [1]).  It's most helpful (to me at least) with larger blocks of code, and especially when there are several levels of nested 'if' statements.

The more things get clumped together, the more difficult it makes things to read to me, and I might use a fair bit more whitespace in general than most do due to that.

It's just my opinion and how I feel, though.  In no way it's going to be a blocker or anything for this, and I'm not exactly arguing which is better overall.  Rather I just wanted to point out that I like the old style.  If you and austin987 feel it's a change for the better, that's already 2 vs 1, and majority probably wins (that, and I trust austin987's decision-making quite a bit).

1. https://en.wikipedia.org/wiki/Indentation_style#Allman_style

**Comment by Kreyren** [comment]
@Chiitoo My opinion is exact opposite meaning that i believe that using `K&R (aka 1TBS) and variants: Stroustrup, Linux kernel, BSD KNF` based on https://en.wikipedia.org/wiki/Indentation_style#Brace_placement_in_compound_statements feels way more readable and effective to me, but then my codestyle is usually something that none else wants to use alike:

```bash
if ! command -v "git" >/dev/null; then die 1 "command 'git' is not executable"; fi

while [ "$#" -gt 0 ]; do case "$1" in
	-f|--force) forced="KREYREN"; shitf '1';;
	-K|--kill) kill_chroot "$2"; exit '1';;
	*)
		mount_required_fs "$1"
		chroot_in "$1" "$2"
		shift
esac; done
```

While trying to prioritize shell syntax in case said code would be required to use on system without dynamic linking (shell only) 
\+ over-quoting like `exit '1'` to define where first non-executable starts and ends where reasoning being good practice and future proofing
+\  Over-sanitization trying to make `trigger -> action` instead of relying on other codeblocks alike:
```bash
# Sanitized git-clone
egit-clone() {
	# SYNOPSIS: $0 [repository] [path]

	# Sanitization
	if ! command -v "git" >/dev/null; then die 1 "command 'git' is not executable"; fi
	## Sanitization for $1
	[[ "$1" != https://*.git ]] && die 1 "${FUNCNAME[0]}: Argument '$1' doesn't match 'https://*.git'"
	# TODO: Sanitize $2

	[ ! -d "$2" ] && (git clone "$1" "$2" && edebug "${FUNCNAME[0]}: cloned '$1' in '$2'" || die 1 "${FUNCNAME[0]}: Unable to clone '$1' in '$2'") || edebug "${FUNCNAME[0]}: Directory '$2' already exists for '$1', skipping.."
}
```
\+ Trying to avoid user-input when possible alike:
```bash
# FUNCTIONS
checkroot () { # Check if executed as root, if not tries to use sudo
	if ! ((EUID)); then
		return
	elif [[ -x "$(command -v sudo)" ]] && [ -n "$KREYREN_CHECKROOT" ]; then
			info "Failed to aquire root permission, trying reinvoking with 'sudo' prefix"
			exec sudo "$0" "$@"
			exit 1
	elif [[ ! -x "$(command -v sudo)" ]] && [ -n "$KREYREN_CHECKROOT" ]; then
		info "Failed to aquire root permission, trying reinvoking as root user."
		exec su -c "$0 $*"
		exit 1
	else
		die 0 "Unable to elevate root access."
	fi
}
```
etc..

so i woudn't want to force my code style of majority prefers Allman since that seems to be favorite choice in UNIX.

**Comment by austin987** [comment]
FWIW, I haven't looked too deeply yet, but I'm considering using `shfmt`, particularly since that lets us delegate formatting to an external utility without having to shim our own checkers:
https://github.com/mvdan/sh

**Pull request closed without merging**
