### PR TITLE
kindle: update to version 1.14.43019

### PR DESCRIPTION
**Pull request by eli-schwartz**
And I think you accidentally removed the call to w_declare_exe when adding vcrun2008, so I added that back as well.

### CODE REVIEW

**Comment by austin987** [comment]
Removing w_declare_exe was intentional, please leave it out.

**Comment by eli-schwartz** [comment]
Done.

Curious: why remove it, all those other apps still have them.

**Comment by austin987** [comment]
I've been removing them when I update surrounding code, haven't done a mass
purge yet, might at some point.

No one that I know of uses them, and they were inconsistent to begin with;
DanK made use of them for a side project that's no longer active, so
there's no need for them.

On Mon, Jan 25, 2016 at 8:58 PM, Eli Schwartz <notifications@github.com>
wrote:

> Done.
>
> Curious: why remove it, all those other apps still have them.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Winetricks/winetricks/pull/598#issuecomment-174791678>
> .
>



-- 
-Austin

**Comment by eli-schwartz** [comment]
> Done.

Bump?

Rebased against latest upstream HEAD (merge conflict).

**Comment by austin987** [comment]
Thanks

**Pull request merged**
