### PR TITLE
Update DirectX9 urls

### LINKED ISSUE #1689: DirectX9 related winetricks don't work anymore.
Looks like the downloadlinks are failing and so also the trick. This counts for example for dsound, directplay, directmusic etc.

Executing mkdir -p /Users/paulthetall/Desktop/test.app/Contents
Using winetricks 20201206-next - sha256sum: 1ad1b01c1f1fc075d9c4362d089f419f7e45edf34fbb239e5cd8d69fb208630b with wine-4.12.1 and WINEARCH=win32
Executing w_do_call directmusic
Executing mkdir -p /Users/paulthetall/Desktop/test.app/Contents
Executing load_directmusic 
------------------------------------------------------
warning: You can specify individual DirectMusic verbs instead. e.g. 'winetricks dmsynth dmusic'
------------------------------------------------------
Executing w_do_call dmband
Executing mkdir -p /Users/paulthetall/Desktop/test.app/Contents
Executing load_dmband 
Executing mkdir -p /Users/paulthetall/.cache/winetricks/directx9
Executing cd /Users/paulthetall/.cache/winetricks/directx9
Downloading https://download.microsoft.com/download/E/E/1/EE17FF74-6C45-4575-9CF4-7FC2597ACD18/directx_feb2010_redist.exe to /Users/paulthetall/.cache/winetricks/directx9
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  1213  100  1213    0     0   1583      0 --:--:-- --:--:-- --:--:--  1583
Executing cd /Users/paulthetall/Desktop/test.app/Wineskin.app/Contents/Resources
------------------------------------------------------
warning: sha256sum mismatch! Rename /Users/paulthetall/.cache/winetricks/directx9/directx_feb2010_redist.exe and try again.
------------------------------------------------------

 Winetricks Commands Finished!!

### PR DESCRIPTION
**Pull request by gverm**
Fixes #1689

### CODE REVIEW

**Comment by tgurr** [comment]
https://files.holarse-linuxgaming.de/mirrors/microsoft/ also mirrors them as well as the archive.org (which has a really slow download speed) https://web.archive.org/web/20201216110836if_/https://download.microsoft.com/download/8/4/A/84A35BF1-DAFE-4AE8-82AF-AD2AE20B6B14/directx_Jun2010_redist.exe but what I actually want to say, they both have a different md5sum than the ones in the pull request.

**Comment by gverm** [comment]
@tgurr You are right. The sha256 for the feb2010 one matched and since there was no sha256 for the jun2010 one I assumed it would match from that website as well. I've updated the PR to use the website you liked for both of them, thanks!

**Comment by austin987** [comment]
Microsoft must've changed it at some point, because I have two different copies on different PCs:
```
austin@austin2 ~ $ sha256sum .cache/winetricks/directx9/directx_Jun2010_redist.exe
8746ee1a84a083a90e37899d71d50d5c7c015e69688a466aa80447f011780c0d  .cache/winetricks/directx9/directx_Jun2010_redist.exe
austin@austin2 ~ $ md5sum .cache/winetricks/directx9/directx_Jun2010_redist.exe
7c1fc2021cf57fed3c25c9b03cd0c31a  .cache/winetricks/directx9/directx_Jun2010_redist.exe
austin@austin2 ~ $ ls -al .cache/winetricks/directx9/directx_Jun2010_redist.exe
-rwxr-xr-x 1 austin austin 100271992 Apr 18  2011 .cache/winetricks/directx9/directx_Jun2010_redist.exe
```

versus
```
austin@debian-desktop ~ $ sha256sum .cache/winetricks/directx9/directx_Jun2010_redist.exe
8c35296f330c0c4e431a7cf155013f3e4abec4a74efd68bb6bfcd76f08c46193  .cache/winetricks/directx9/directx_Jun2010_redist.exe
austin@debian-desktop ~ $ md5sum .cache/winetricks/directx9/directx_Jun2010_redist.exe
4e41372e8775e8025be013480b0629b3  .cache/winetricks/directx9/directx_Jun2010_redist.exe
austin@debian-desktop ~ $ ls -al .cache/winetricks/directx9/directx_Jun2010_redist.exe
-rwxr-xr-x 1 austin austin 100273008 Jun  4  2010 .cache/winetricks/directx9/directx_Jun2010_redist.exe
```

I think using the newer version (8c35296f330c0c4e431a7cf155013f3e4abec4a74efd68bb6bfcd76f08c46193 / April 2011 / 7c1fc2021cf57fed3c25c9b03cd0c31a) makes the most sense.

Thanks @gverm and @tgurr!

**Comment by TBBle** [comment]
It looks like MS have republished directx_Jun2010_redist.exe at the previous URL, now SHA-256 signed. directx_feb2010_redist.exe hasn't reappeared.

**Comment by kaznovac** [comment]
official microsoft's directx_jun2010
https://download.microsoft.com/download/8/4/a/84a35bf1-dafe-4ae8-82af-ad2ae20b6b14/directx_Jun2010_redist.exe


Version:
9.29.1974.1

Date Published:
7/15/2024

File Name:
directx_Jun2010_redist.exe

File Size:
95.6 MB

`sha256sum directx_Jun2010_redist.exe`
```
053f76dcbb28802e23341b6a787e3b0791c0fa5c8d4d011b1044172dbf89c73b  directx_Jun2010_redist.exe
```

**Pull request merged**
