### PR TITLE
vcrun2015: Refactor and workaround for 47565

### PR DESCRIPTION
**Pull request by Kreyren**
Fixes: https://github.com/Winetricks/winetricks/issues/1407#issuecomment-554479859

Depends on tests from @developedby

Signed-off-by: Jacob Hrbek <kreyren@rixotstudio.cz>

### CODE REVIEW

**Comment by Kreyren** [comment]
Tested locally

```console
$ su -c "rm -r /home/demo/test/" ; WINEARCH="win32" WINEPREFIX="/home/demo/test" /usr/src/kreytricks/src/winetricks vcrun2015
Password: 
Using winetricks 20190912-next - sha256sum: 224ad0224629fd64ce2dd43baf3e23051eea12f8706458943b31688fccded1c9 with wine-4.19 (Staging) and WINEARCH=win32
Executing w_do_call vcrun2015
Executing load_vcrun2015 
Current Wine does not have Wine bug 37781, so not applying workaround
Current Wine does not have Wine bug 37781, so not applying workaround
/usr/src/kreytricks/src/winetricks: 11893: w_debug: not found
Using native,builtin override for following DLLs: api-ms-win-crt-private-l1-1-0 api-ms-win-crt-conio-l1-1-0 api-ms-win-crt-heap-l1-1-0 api-ms-win-crt-locale-l1-1-0 api-ms-win-crt-math-l1-1-0 api-ms-win-crt-runtime-l1-1-0 api-ms-win-crt-stdio-l1-1-0 api-ms-win-crt-time-l1-1-0 atl140 concrt140 msvcp140 msvcr140 ucrtbase vcomp140 vcruntime140
Executing wine regedit C:\windows\Temp\_vcrun2015\override-dll.reg
------------------------------------------------------
Working around wine bug 47565 
------------------------------------------------------
Executing cabextract -q --directory=/home/demo/test/dosdevices/c:/windows/temp/_vcrun2015 /home/demo/.cache/winetricks/vcrun2015/vc_redist.x86.exe
Executing cabextract -q --directory=/home/demo/test/dosdevices/c:/windows/temp/_vcrun2015 /home/demo/test/dosdevices/c:/windows/temp/_vcrun2015/a10
/home/demo/test/dosdevices/c:/windows/temp/_vcrun2015/a10: WARNING; possible 16128 extra bytes at end of file.
Executing cabextract -q --directory=/home/demo/test/dosdevices/c:/windows/temp/_vcrun2015 /home/demo/test/dosdevices/c:/windows/temp/_vcrun2015/a11
/home/demo/test/dosdevices/c:/windows/temp/_vcrun2015/a11: WARNING; possible 16128 extra bytes at end of file.
Executing cp /home/demo/test/dosdevices/c:/windows/temp/_vcrun2015/concrt140.dll /home/demo/test/dosdevices/c:/windows/system32/concrt140.dll
Executing cp /home/demo/test/dosdevices/c:/windows/temp/_vcrun2015/mfc140.dll /home/demo/test/dosdevices/c:/windows/system32/mfc140.dll
Executing cp /home/demo/test/dosdevices/c:/windows/temp/_vcrun2015/mfc140u.dll /home/demo/test/dosdevices/c:/windows/system32/mfc140u.dll
Executing cp /home/demo/test/dosdevices/c:/windows/temp/_vcrun2015/mfcm140.dll /home/demo/test/dosdevices/c:/windows/system32/mfcm140.dll
Executing cp /home/demo/test/dosdevices/c:/windows/temp/_vcrun2015/mfcm140u.dll /home/demo/test/dosdevices/c:/windows/system32/mfcm140u.dll
Executing cp /home/demo/test/dosdevices/c:/windows/temp/_vcrun2015/msvcp140.dll /home/demo/test/dosdevices/c:/windows/system32/msvcp140.dll
Executing cp /home/demo/test/dosdevices/c:/windows/temp/_vcrun2015/vcamp140.dll /home/demo/test/dosdevices/c:/windows/system32/vcamp140.dll
Executing cp /home/demo/test/dosdevices/c:/windows/temp/_vcrun2015/vccorlib140.dll /home/demo/test/dosdevices/c:/windows/system32/vccorlib140.dll
Executing cp /home/demo/test/dosdevices/c:/windows/temp/_vcrun2015/vcomp140.dll /home/demo/test/dosdevices/c:/windows/system32/vcomp140.dll
Executing cp /home/demo/test/dosdevices/c:/windows/temp/_vcrun2015/vcruntime140.dll /home/demo/test/dosdevices/c:/windows/system32/vcruntime140.dll
Executing cp /home/demo/test/dosdevices/c:/windows/temp/_vcrun2015/api_ms_win_crt_conio_l1_1_0.dll /home/demo/test/dosdevices/c:/windows/system32/api-ms-win-crt-conio-l1-1-0.dll
Executing cp /home/demo/test/dosdevices/c:/windows/temp/_vcrun2015/api_ms_win_crt_heap_l1_1_0.dll /home/demo/test/dosdevices/c:/windows/system32/api-ms-win-crt-heap-l1-1-0.dll
Executing cp /home/demo/test/dosdevices/c:/windows/temp/_vcrun2015/api_ms_win_crt_locale_l1_1_0.dll /home/demo/test/dosdevices/c:/windows/system32/api-ms-win-crt-locale-l1-1-0.dll
Executing cp /home/demo/test/dosdevices/c:/windows/temp/_vcrun2015/api_ms_win_crt_math_l1_1_0.dll /home/demo/test/dosdevices/c:/windows/system32/api-ms-win-crt-math-l1-1-0.dll
Executing cp /home/demo/test/dosdevices/c:/windows/temp/_vcrun2015/api_ms_win_crt_runtime_l1_1_0.dll /home/demo/test/dosdevices/c:/windows/system32/api-ms-win-crt-runtime-l1-1-0.dll
Executing cp /home/demo/test/dosdevices/c:/windows/temp/_vcrun2015/api_ms_win_crt_stdio_l1_1_0.dll /home/demo/test/dosdevices/c:/windows/system32/api-ms-win-crt-stdio-l1-1-0.dll
Executing cp /home/demo/test/dosdevices/c:/windows/temp/_vcrun2015/ucrtbase.dll /home/demo/test/dosdevices/c:/windows/system32/ucrtbase.dll
```

**Comment by developedby** [comment]
Works here

    nicolas@nicolas-solus /run/media/nicolas/Coisas/Jogos/teste $ WINEPREFIX=/run/media/nicolas/Coisas/Jogos/teste WINEARCH=win32 winetricks vcrun2015
    Using winetricks 20190912-next - sha256sum: 224ad0224629fd64ce2dd43baf3e23051eea12f8706458943b31688fccded1c9 with wine-4.19 and WINEARCH=win32
    Executing w_do_call vcrun2015
    Executing load_vcrun2015 
    Current Wine does not have Wine bug 37781, so not applying workaround
    Current Wine does not have Wine bug 37781, so not applying workaround
    /usr/bin/winetricks: line 11893: w_debug: command not found
    Using native,builtin override for following DLLs: api-ms-win-crt-private-l1-1-0 api-ms-win-crt-conio-l1-1-0 api-ms-win-crt-heap-l1-1-0 api-ms-win-crt-locale-l1-1-0 api-ms-win-crt-math-l1-1-0 api-ms-win-crt-runtime-l1-1-0 api-ms-win-crt-stdio-l1-1-0 api-ms-win-crt-time-l1-1-0 atl140 concrt140 msvcp140 msvcr140 ucrtbase vcomp140 vcruntime140
    Executing wine regedit C:\windows\Temp\_vcrun2015\override-dll.reg
    ------------------------------------------------------
    Working around wine bug 47565 
    ------------------------------------------------------
    Executing cabextract -q --directory=/run/media/nicolas/Coisas/Jogos/teste/dosdevices/c:/windows/temp/_vcrun2015 /home/nicolas/.cache/winetricks/vcrun2015/vc_redist.x86.exe
    Executing cabextract -q --directory=/run/media/nicolas/Coisas/Jogos/teste/dosdevices/c:/windows/temp/_vcrun2015 /run/media/nicolas/Coisas/Jogos/teste/dosdevices/c:/windows/temp/_vcrun2015/a10
    /run/media/nicolas/Coisas/Jogos/teste/dosdevices/c:/windows/temp/_vcrun2015/a10: WARNING; possible 16128 extra bytes at end of file.
    Executing cabextract -q --directory=/run/media/nicolas/Coisas/Jogos/teste/dosdevices/c:/windows/temp/_vcrun2015 /run/media/nicolas/Coisas/Jogos/teste/dosdevices/c:/windows/temp/_vcrun2015/a11
    /run/media/nicolas/Coisas/Jogos/teste/dosdevices/c:/windows/temp/_vcrun2015/a11: WARNING; possible 16128 extra bytes at end of file.
    Executing cp /run/media/nicolas/Coisas/Jogos/teste/dosdevices/c:/windows/temp/_vcrun2015/concrt140.dll /run/media/nicolas/Coisas/Jogos/teste/dosdevices/c:/windows/system32/concrt140.dll
    Executing cp /run/media/nicolas/Coisas/Jogos/teste/dosdevices/c:/windows/temp/_vcrun2015/mfc140.dll /run/media/nicolas/Coisas/Jogos/teste/dosdevices/c:/windows/system32/mfc140.dll
    Executing cp /run/media/nicolas/Coisas/Jogos/teste/dosdevices/c:/windows/temp/_vcrun2015/mfc140u.dll /run/media/nicolas/Coisas/Jogos/teste/dosdevices/c:/windows/system32/mfc140u.dll
    Executing cp /run/media/nicolas/Coisas/Jogos/teste/dosdevices/c:/windows/temp/_vcrun2015/mfcm140.dll /run/media/nicolas/Coisas/Jogos/teste/dosdevices/c:/windows/system32/mfcm140.dll
    Executing cp /run/media/nicolas/Coisas/Jogos/teste/dosdevices/c:/windows/temp/_vcrun2015/mfcm140u.dll /run/media/nicolas/Coisas/Jogos/teste/dosdevices/c:/windows/system32/mfcm140u.dll
    Executing cp /run/media/nicolas/Coisas/Jogos/teste/dosdevices/c:/windows/temp/_vcrun2015/msvcp140.dll /run/media/nicolas/Coisas/Jogos/teste/dosdevices/c:/windows/system32/msvcp140.dll
    Executing cp /run/media/nicolas/Coisas/Jogos/teste/dosdevices/c:/windows/temp/_vcrun2015/vcamp140.dll /run/media/nicolas/Coisas/Jogos/teste/dosdevices/c:/windows/system32/vcamp140.dll
    Executing cp /run/media/nicolas/Coisas/Jogos/teste/dosdevices/c:/windows/temp/_vcrun2015/vccorlib140.dll /run/media/nicolas/Coisas/Jogos/teste/dosdevices/c:/windows/system32/vccorlib140.dll
    Executing cp /run/media/nicolas/Coisas/Jogos/teste/dosdevices/c:/windows/temp/_vcrun2015/vcomp140.dll /run/media/nicolas/Coisas/Jogos/teste/dosdevices/c:/windows/system32/vcomp140.dll
    Executing cp /run/media/nicolas/Coisas/Jogos/teste/dosdevices/c:/windows/temp/_vcrun2015/vcruntime140.dll /run/media/nicolas/Coisas/Jogos/teste/dosdevices/c:/windows/system32/vcruntime140.dll
    Executing cp /run/media/nicolas/Coisas/Jogos/teste/dosdevices/c:/windows/temp/_vcrun2015/api_ms_win_crt_conio_l1_1_0.dll /run/media/nicolas/Coisas/Jogos/teste/dosdevices/c:/windows/system32/api-ms-win-crt-conio-l1-1-0.dll
    Executing cp /run/media/nicolas/Coisas/Jogos/teste/dosdevices/c:/windows/temp/_vcrun2015/api_ms_win_crt_heap_l1_1_0.dll /run/media/nicolas/Coisas/Jogos/teste/dosdevices/c:/windows/system32/api-ms-win-crt-heap-l1-1-0.dll
    Executing cp /run/media/nicolas/Coisas/Jogos/teste/dosdevices/c:/windows/temp/_vcrun2015/api_ms_win_crt_locale_l1_1_0.dll /run/media/nicolas/Coisas/Jogos/teste/dosdevices/c:/windows/system32/api-ms-win-crt-locale-l1-1-0.dll
    Executing cp /run/media/nicolas/Coisas/Jogos/teste/dosdevices/c:/windows/temp/_vcrun2015/api_ms_win_crt_math_l1_1_0.dll /run/media/nicolas/Coisas/Jogos/teste/dosdevices/c:/windows/system32/api-ms-win-crt-math-l1-1-0.dll
    Executing cp /run/media/nicolas/Coisas/Jogos/teste/dosdevices/c:/windows/temp/_vcrun2015/api_ms_win_crt_runtime_l1_1_0.dll /run/media/nicolas/Coisas/Jogos/teste/dosdevices/c:/windows/system32/api-ms-win-crt-runtime-l1-1-0.dll
    Executing cp /run/media/nicolas/Coisas/Jogos/teste/dosdevices/c:/windows/temp/_vcrun2015/api_ms_win_crt_stdio_l1_1_0.dll /run/media/nicolas/Coisas/Jogos/teste/dosdevices/c:/windows/system32/api-ms-win-crt-stdio-l1-1-0.dll
    Executing cp /run/media/nicolas/Coisas/Jogos/teste/dosdevices/c:/windows/temp/_vcrun2015/ucrtbase.dll /run/media/nicolas/Coisas/Jogos/teste/dosdevices/c:/windows/system32/ucrtbase.dll
    You opted in, so reporting 'w_workaround_wine_bug-47565 vcrun2015 ' to the winetricks maintainer so he knows which winetricks verbs get used and which don't.  Use --optout to disable future reports.

**Comment by Kreyren** [comment]
> /usr/bin/winetricks: line 11893: w_debug: command not found

Uses; https://github.com/Winetricks/winetricks/pull/1339

**Comment by tannisroot** [comment]
The manual extraction workaround isn't even needed anymore, the bug was fixed in 4.15.

**Comment by Kreyren** [comment]
> The manual extraction workaround isn't even needed anymore, the bug was fixed in 4.15.

Which makes the <4.15 still affected

**Comment by austin987** [comment]
No, only 4.12-4.15 are affected. However, given that those are now outdated development versions, and that this PR was fundamentally wrong to begin with, I don't think it's worth worrying about.

**Pull request closed without merging**
