### PR TITLE
leagueoflegends: new verb

### PR DESCRIPTION
**Pull request by Kreyren**
DO NOT MERGE!  - Game got updated and previous workarounds no longer works

Leagueoflegendsbanner

Attempt to add leagueoflegends compatibility for winetricks

NOTICE: is it reported that wine-staging >4,15 with provided patches has runtime issues https://bugs.winehq.org/show_bug.cgi?id=47198#c81

- (resolved) DXVK should give us 120~180% performance boost compared to 100% on 'optimized' windows/mac assuming usage of wrapper for DX9 to run DX11 that runs on vulkan. (https://github.com/PhoenicisOrg/scripts/pull/797)

- (Won't be resolved immediately, proceed without) checksum (https://boards.na.leagueoflegends.com/en/c/general-discussion/tZ4uPccJ-checksum-for-league-of-legends-installer)

- Hotfix https://github.com/Winetricks/winetricks/pull/1335#issuecomment-534690633

Blocked (hotfixed) by https://github.com/Winetricks/winetricks/pull/1338 assuming that there is no way to make winetricks to invoke WINE after verb is called where function `winetricks_init()` is conflicting due to the:
https://github.com/Winetricks/winetricks/blob/f54242371e4917c94bfc01b87ea34727ad9ab09c/src/winetricks#L5106

DEPENDS: https://github.com/Winetricks/winetricks/pull/1354
DEPENDS: https://github.com/Winetricks/winetricks/pull/1351 (hotfixed)
BLOCKED BY: https://github.com/Winetricks/winetricks/pull/1359 (hotfixed)

NOTICE: Affected by https://bugs.winehq.org/show_bug.cgi?id=47198
NOTICE: Affected by https://bugs.winehq.org/show_bug.cgi?id=47765

Signed-off-by: Jacob Hrbek <kreyren@rixotstudio.cz>

---

# Notice to winetricks maintainers

Currently not fully functional due used to the workaround for winebug 47198 where workarounds that require reinvoking the script, but allow wineapp installation 

Uses wineappimagebuilder, but is able to work without it ($WINETRICKS_BUILD_WINE unset by default)

Requesting review/approval for following:
- Documentation in winetricks wiki on https://github.com/Winetricks/winetricks/pull/1335#issuecomment-534035206
- Proposed solution for workaround in case providing wine in sandboxed environment like `AppImage` is not sufficient (currently is it. but this solution could make it possible to be used on FreeBSD/MacOS based on conversation in https://github.com/Winetricks/winetricks/pull/1318). 
- Note that current merge request is using https://github.com/Winetricks/winetricks/pull/1338 to get cygwin compatibility which is in works.
- Note that AHK script may be possible to make log-in automatic this merge request adds only comment with TODO for this atm.
- Please squash using github with first comment in this merge request excluding image at the top and "Notice to winetricks maintainers"
- Notice that this installer is meant to be used with provided WINE which is based on available info impossible with winetricks (https://github.com/Winetricks/winetricks/pull/1335#issuecomment-534910844) this is being tracked in https://github.com/Winetricks/winetricks/issues/1344 and i'm working on contrib

I've made lots of changes let me know if it's hard to track the changes and i stage them in multiple merge requests or request a more effective way to handle review (if needed).

### CODE REVIEW

**Comment by Kreyren** [comment]
RESERVED

**Comment by Kreyren** [comment]
Proposed solution to get League Of Legends working on any system:

Gentoo Wrapper (WIP)

Theory: Chroot in gentoo, configure xorg and run the game with patches, the result is new WINE window with game that is working as expected + Allows further optimization

```bash
case "$leagueoflegends_workaround_47198" in
    kreyren) # Getting required patchset using gentoo wrapper
      # FUNCTIONS
      ## Error handling
      e_debug() { [ -n "$debug" ] && (printf "$1" || w_die "printf returned 1") || true ; }
      ## check_exec $1
      e_check_exec() { if ! command -v "$1" >/dev/null; then w_die "Command '$1' is not executable" ; fi ; }
      sanitize_mount_directory() { # Sanitization for Mount Directory variable
      	[ -z "$1" ] && w_die "Function ${FUNCNAME[0]} expects argument with path to mount directory which is not provided"
      	[ ! -d "$1" ] && w_die "First argument \'$1\' of function \'${FUNCNAME[0]}\' is not a valid directory"
      	[[ "$1" != /mnt/* ]] && w_warn "Mount directories should be mounted in /mnt directory not $1" # TODO: regex first directory if possible
      	[ ! -e "${1}/etc" ] && [ -z "$forced" ] && die "Unable to find /etc directory in $1 directory, assuming invalid mount directory, use --force to override if needed."
      }
      mount_required_fs() { # Mount required filesystems
      	## Sanitization - Expecting 1="/mnt/something"
      	sanitize_mount_directory "$1"
      	## Action
        ### TODO: Fix root elevation
      	if ! grep -qF "${1}/dev" '/proc/mounts';	then (sudo mount --rbind /dev "${1}/dev/" && sudo mount --make-rslave "${1}/dev") || w_die "Unable to mount /dev to \'${1}/dev\' as rbind which is required";	fi
      	if ! grep -qF "${1}/dev" '/proc/mounts';	then sudo mount --bind /sys "${1}/sys/" || w_die "Unable to mount /sys to \'${1}/sys\' as bind which is required";	fi
      	if ! grep -qF "${1}/tmp" '/proc/mounts';	then (sudo mount --rbind /tmp "${1}/tmp" && sudo mount --make-rslave "${1}/tmp") || w_die "Unable to mount /tmp to \'${1}/tmp\' as rbind which is required";	fi
      	if ! grep -qF "${1}/proc" '/proc/mounts';	then sudo mount --types proc none "${1}/proc/" || w_die "Unable to mount \'${1}/proc\' on none which is required"; fi
      }

      # ACTION
      ## Sanitization
      ### Sanitization for debian to pass
      grep -qF 'NAME="Debian GNU/Linux"' /etc/os-release && export PATH="${PATH}:/sbin"
      e_check_exec 'mount'
      e_check_exec 'chroot'
      e_check_exec 'wget'
      e_check_exec 'chown'
      e_check_exec 'stat'
      my_user="$([ "$USER" = 'root' ] && printf "larry" || printf "$USER")"
      [ ! -d "${W_CACHE}/leagueoflegends/kreyren/" ] && (mkdir -p "${W_CACHE}/leagueoflegends/kreyren/" || w_die "Unable to make a new directory in "${W_CACHE}/leagueoflegends/kreyren/"")
      ## Check if directory is present
      [ -z "$MY_WINEPREFIX" ] && w_die "Specify MY_WINEPREFIX to proceed with this installation"
      [ ! -d "$MY_WINEPREFIX" ] && (mkdir "$MY_WINEPREFIX" && w_info "Created a new directory in $MY_WINETRICKS" || w_die "Unable to make a new directory in $MY_WINETRICKS")

      ## Export gentoo on $MY_WINEPREFIX if not present
      if [ ! -e "${MY_WINEPREFIX}/etc/portage" ]]; then
        ## Fetch definitions for file, why not use current like exherbo's current naming and make my job easier..
        if [ ! -e "${MY_WINEPREFIX}/gentoo_info" ]; then
          wget 'https://gentoo.osuosl.org/releases/amd64/autobuilds/latest-stage3-amd64.txt' -O "${W_CACHE}/leagueoflegends/kreyren/gentoo_info" || w_die "Unable to fetch definitions for gentoo tarbar name."
        elif [ -e "${MY_WINEPREFIX}/gentoo_info" ]; then
          w_info "file '${MY_WINEPREFIX}/gentoo_info' is present"
        fi

        ### Definitions
        gentoo_tarbar="http://distfiles.gentoo.org/releases/amd64/autobuilds/$(cat ${W_CACHE}/leagueoflegends/kreyren/gentoo_info | grep -o "[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]T[0-9][0-9][0-9][0-9][0-9][0-9]Z/stage3-amd64-[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]T[0-9][0-9][0-9][0-9][0-9][0-9]Z.tar.xz")"
          gt="${gentoo_tarbar}"
        #### TODO: Fix useless cat
        gentoo_file_name="$(cat "${W_CACHE}/leagueoflegends/kreyren/gentoo_info" | grep -o "stage3-amd64-[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]T[0-9][0-9][0-9][0-9][0-9][0-9]Z.tar.xz")"
          qfn="${gentoo_file_name}" # Doesn't work for some reason..

        ### Actual fetch
        if [ ! -e "${MY_WINEPREFIX}/$gentoo_file_name" ]; then
          wget "$gt" -P "${MY_WINEPREFIX}" || w_die "Unable to fetch Gentoo tarbar"
        elif [ -e "${MY_WINEPREFIX}/$gentoo_file_name" ]; then
          w_info "Tarbar \'${MY_WINEPREFIX}/$gentoo_file_name\' is present"
        fi
        tar -xpf "${MY_WINEPREFIX}/$gentoo_file_name" --directory="$MY_WINEPREFIX" || w_die "Unable to extract gentoo tarbar"
        mv "${MY_WINEPREFIX}/$gentoo_file_name" "/tmp/winetricks/$gentoo_file_name" || warn "ERROR: Unable to safely remove \'${MY_WINEPREFIX}/$gentoo_file_name\'"

      elif [ -e "${MY_WINEPREFIX}/etc/portage" ]; then
      w_info "Gentoo is already extracted."
    fi

    ## Make mount points
    mount_required_fs "$MY_WINEPREFIX"

    ## Configure ${MY_WINEPREFIX}/etc/resolv.conf
    if [[ "$(sed -n 1p "${MY_WINEPREFIX}/etc/resolv.conf")" != "nameserver 1.1.1.1"  ]]; then
      printf "nameserver 1.1.1.1\nnameserver1.0.0.1\nnameserver 2606:4700:4700::1111\nnameserver 2606:4700:4700::1001" > "${MY_WINEPREFIX}/etc/resolv.conf" || w_die "Unable to make ${MY_WINEPREFIX}/etc/resolv.conf configuration"
    elif [[ $(sed -n 1p "${MY_WINEPREFIX}/etc/resolv.conf") == "nameserver 1.1.1.1"  ]]; then
      printf "\'${MY_WINEPREFIX}etc/resolv.conf\' is configured"
    fi

    ## Adapting Argent Linux binhost
    if [[ "$(cat "${MY_WINEPREFIX}/etc/portage/make.conf" | grep -o "PORTAGE_BINHOST="http://pkgwork.argentlinux.io/argentwork/binhost/x64/"")" != "PORTAGE_BINHOST="http://pkgwork.argentlinux.io/argentwork/binhost/x64/"" ]]; then
      printf "PORTAGE_BINHOST="http://pkgwork.argentlinux.io/argentwork/binhost/x64/"" >> "${MY_WINEPREFIX}/etc/portage/make.conf"
    elif [[ "$(cat "${MY_WINEPREFIX}/etc/portage/make.conf" | grep -o "PORTAGE_BINHOST="http://pkgwork.argentlinux.io/argentwork/binhost/x64/"")" == "PORTAGE_BINHOST="http://pkgwork.argentlinux.io/argentwork/binhost/x64/"" ]]; then
      w_info "Argent linux binhost is configured, thanks Stephan Christian"
    fi

    ## Adapting Andrew Wessie's patches
    [ ! -e "${MY_WINEPREFIX}/etc/portage/patches/app-emulation/wine-staging" ] && (mkdir -p "${MY_WINEPREFIX}/etc/portage/patches/app-emulation/wine-staging" || w_die "Unable to make a new directory in "${MY_WINEPREFIX}/etc/portage/patches/app-emulation/wine-staging"")
    [ ! -e "${MY_WINEPREFIX}/etc/portage/patches/app-emulation/wine-staging/01-pakman.diff" ] && wget 'https://bugs.winehq.org/attachment.cgi?id=64481' -O "${MY_WINEPREFIX}/etc/portage/patches/app-emulation/wine-staging/01-pakman.diff"
    [ ! -e "${MY_WINEPREFIX}/etc/portage/patches/app-emulation/wine-staging/02-pakman.diff" ] && wget 'https://bugs.winehq.org/attachment.cgi?id=64482' -O "${MY_WINEPREFIX}/etc/portage/patches/app-emulation/wine-staging/02-pakman.diff"

    ## Configure bobwya repository which is recommended for wine
    ### TODO: Sanitize
    if [ ! -e "${MY_WINEPREFIX}/etc/portage/repos.conf/bobwya.conf" ] && [[ "$(cat "${MY_WINEPREFIX}/etc/portage/repos.conf/bobwya.conf")" != "$(printf "[bobwya]\nlocation = /usr/bobwya-repo/\nsync-type = git\nsync-uri = git@github.com:bobwya/bobwya.git\nauto-sync = yes")" ]]; then
      printf "[bobwya]\nlocation = /usr/bobwya-repo/\nsync-type = git\nsync-uri = git@github.com:bobwya/bobwya.git\nauto-sync = yes" > "${MY_WINEPREFIX}/etc/portage/repos.conf/bobwya.conf" || w_die "Unable to write into \'${MY_WINEPREFIX}/etc/portage/repos.conf/bobwya.conf\'"
    elif [ -e "${MY_WINEPREFIX}/etc/portage/repos.conf/bobwya.conf" ] && [[ "$(cat "${MY_WINEPREFIX}/etc/portage/repos.conf/bobwya.conf")" == "$(printf "[bobwya]\nlocation = /usr/bobwya-repo/\nsync-type = git\nsync-uri = git@github.com:bobwya/bobwya.git\nauto-sync = yes")" ]]; then
      w_info "Bobwya repository has been configured"
    fi

    ## Sync gentoo repository
    ### TODO: Future-proof for $PORTDIR
    [ ! -e "${MY_WINEPREFIX}/var/db/repos/app-emulation/" ] && chroot "${MY_WINEPREFIX}" "emerge --sync --quiet" || w_die "FATAL: Unable to sync gentoo repository"

    ## Creating user account
    if [[ "$(chroot "${MY_WINEPREFIX}" 'cat /etc/group' | grep -o "$my_user" -m 1)" != "$my_user" ]]; then
      chroot "${MY_WINEPREFIX}" "useradd -m -G users,wheel,audio -s /bin/bash $my_user" || w_die "Unable to make new user \'$my_user\' on chroot"
    elif [[ "$(chroot "${MY_WINEPREFIX}" "cat /etc/group" | grep -o "$my_user" -m 1)" == "$my_user" ]]; then
      w_info "Account \'$my_user\' is present in chroot\n"
    fi

    ## Configure Xorg
    xauth 'extract' "${MY_WINEPREFIX}/home/${my_user}/.Xauthority" "$(hostname)/unix:0" && edebug "FIXME: .Xauthority has been exported." || w_die "Unable to export .Xauthority"
    ### Install Xorg if not present already
    chroot "${MY_WINEPREFIX}" "emerge --noreplace --getbinpkg="y" xorg-server" || w_die "FATAL: Unable to install xorg-server in gentoo chroot"
    ### Add localhost into chroot
    chroot "${MY_WINEPREFIX}" "env XAUTHORITY="/home/${my_user}/.Xauthority" xhost +localhost" || w_die "FATAL: Unable to add localhost into xhost"
    ### Fix permission of /home/${my_user}/.Xauthority
    chroot "${MY_WINEPREFIX}" "bash -c "chown "${my_user}:${my_user}" "/home/${my_user}/.Xauthority""" || w_die "FATAL: Unable to transfer ownership of /home/${my_user}/.Xauthority to ${my_user}"
    ### Creating /home/${my_user}/Downloads
    if [[ ! -e "${MY_WINEPREFIX}/home/${my_user}/Downloads" ]]; then
      chroot "${MY_WINEPREFIX}" "su "$my_user" -c "mkdir "/home/${my_user}/Downloads""" || w_die "FATAL: Unable to make directory in /home/${my_user}/Downloads"
    elif [[ -e "${MY_WINEPREFIX}/home/${my_user}/Downloads" ]]; then
      w_info "Directory \'${MY_WINEPREFIX}/home/${my_user}/Downloads\' is present"
    fi

    ### Check if wine is present, else install it
    if [[ ! -h "${MY_WINEPREFIX}/usr/bin/wine" ]]; then
      chroot "${MY_WINEPREFIX}" "emerge =app-emulation/wine-staging-9999::bobwya --quiet" || w_die "Unable to compile wine"
    elif [ -h "${MY_WINEPREFIX}/usr/bin/wine" ]; then
      w_info "wine is already installed in gentoo chroot"
    elif [ -e "${MY_WINEPREFIX}/usr/bin/wine" ]; then
      w_w_die "FATAL: File ${MY_WINEPREFIX}/usr/bin/wine is not expected to be regular file, symlink is expected."
    fi

    ### Get winetricks
    if [ ! -e "${MY_WINEPREFIX}/usr/bin/winetricks" ]; then
      chroot "$MY_WINEPREFIX" "emerge =app-emulation/winetricks-9999 --quiet" || w_die "FATAL: Unable to enoch merge winetricks."
    elif [ -e "${MY_WINEPREFIX}/usr/bin/winetricks" ]; then
      w_info "Winetricks is already intalled in gentoo chroot"
    fi

    ### Creating /home/${my_user}/Downloads
    if [ ! -e "${MY_WINEPREFIX}/home/${my_user}/Downloads" ]; then
      chroot "$MY_WINEPREFIX" "su "$my_user" -c "mkdir /home/${my_user}/Downloads"" || w_die "Unable to make directory in /home/${my_user}/Downloads"
    elif [ -e "${MY_WINEPREFIX}/home/${my_user}/Downloads" ]; then
      edebug "Directory \'${MY_WINEPREFIX}/home/${my_user}/Downloads\' is already present"
    fi

    ### Check if $HOME/Games/LeagueOfLegends is present
    if [ ! -e "${MY_WINEPREFIX}/home/${my_user}/Games/" ]; then
      chroot "$MY_WINEPREFIX" "su "$my_user" -c "mkdir -p /home/${my_user}/Games/"" || w_die "Unable to make new game directory on chroot"
    elif [ -e "${MY_WINEPREFIX}/home/${my_user}/Games/" ]; then
      edebug "Directory \'${MY_WINEPREFIX}/home/${my_user}/Games/\' is present"
    fi

    ### Download the game
    if [ ! -e "${MY_WINEPREFIX}/home/${my_user}/Downloads/lol_installer.exe" ]; then
      chroot "$MY_WINEPREFIX" "su "$my_user" -c "wget 'https://riotgamespatcher-a.akamaihd.net/releases/live/installer/deploy/League%20of%20Legends%20installer%20EUNE.exe' -O "/home/${my_user}/Downloads/lol_installer.exe""" || w_die "Unable to fetch LeagueOfLegends installer"
    elif [[ -e ${MY_WINEPREFIX}/home/${my_user}/Downloads/lol_installer.exe ]]; then
      edebug "lol_installer.exe is present"
    fi

    ### Install the game
    if [ ! -e "${MY_WINEPREFIX}/home/${my_user}/Games/LeagueOfLegends/drive_c/Riot Games/League of Legends/LeagueClient.exe" ]; then
      w_warn "DO NOT CHANGE DEFAULT PATH OF LEAGUE OF LEGENDS INSTALLATION!!"
      chroot "$MY_WINEPREFIX" su "$my_user" -c "env XAUTHORITY="/home/${my_user}/.Xauthority" WINEDEBUG="fixme-all" MY_WINEPREFIX="/home/${my_user}/Games/LeagueOfLegends" wine /home/${my_user}/Downloads/lol_installer.exe" || w_die "FATAL: Unable to install LeagueOfLegends"
      w_info "LeagueOfLegends was installed."
    elif [ -e "${MY_WINEPREFIX}/home/${my_user}/Games/LeagueOfLegends/drive_c/Riot Games/League of Legends/LeagueClient.exe" ]; then
      edebug "LeagueOfLegends is already installed."
    fi

    ## Run the game
    if [ -e "${MY_WINEPREFIX}/home/${my_user}/Games/LeagueOfLegends/drive_c/Riot Games/League of Legends/LeagueClient.exe" ]; then
      chroot "$MY_WINEPREFIX" "su "$my_user" -c "env XAUTHORITY="/home/${my_user}/.Xauthority" WINEDEBUG="fixme-all" MY_WINEPREFIX="/home/${my_user}/Games/LeagueOfLegends" wine "/home/${my_user}/Games/LeagueOfLegends/drive_c/Riot Games/League of Legends/LeagueClient.exe""" || w_die "Unable to run LeagueOfLegends"
    elif [ ! -e "${MY_WINEPREFIX}/home/${my_user}/Games/LeagueOfLegends/drive_c/Riot Games/League of Legends/LeagueClient.exe" ]; then
      w_warn "This error should never happend."
    fi
    ;;
    *)
    ...
  esac
```

**Comment by Kreyren** [comment]
Tested locally works on platinum:
image

**Comment by Kreyren** [comment]
Travis complains about possible bashism because i'm using `read 'var'` fixing on request.

@austin987 Ready for review + requesting review for https://github.com/Winetricks/winetricks/pull/1335#issuecomment-534035206 to be added in github wiki so that diagnosing league of legends issues is easier.

Note alternative method to handle wine patches https://github.com/Winetricks/winetricks/pull/1335#issuecomment-534077681 where current is sufficient.

**Comment by Kreyren** [comment]
Question: How do i make winetricks to NOT make a new wineprefix using built-in wine on startup ? It's expected to use provided WINE on demand.

**Comment by axredneck** [comment]
> Question: How do i make winetricks to NOT make a new wineprefix using built-in wine on startup ? It's expected to use provided WINE on demand.

`env WINE="/path/to/your/wine" winetricks yourverb`
This?

**Comment by Kreyren** [comment]
> > Question: How do i make winetricks to NOT make a new wineprefix using built-in wine on startup ? It's expected to use provided WINE on demand.
> 
> `env WINE="/path/to/your/wine" winetricks yourverb`
> This?

Yes, but without the need for end-user to set WINE variable since it generates a new wineprefix in `~/.wine` if that is not already present and then it proceeds with a logic for leagueoflegends

assuming that this verb is using provided precompiled wine untill bug 47198 is resolved which makes the provided wine reconfigure wineprefix on instalation for different wine which is annoying.. 

So i'm not sure if this should be changed within winetricks to adapt for this situation or if there is winetricks way to do this

**Comment by Kreyren** [comment]
NOTICE:
```
wine client error:0: version mismatch 589/586.
Your wine binary was not upgraded correctly,
or you have an older one somewhere in your PATH.
Or maybe the wrong wineserver is still running?
```

Is outputed if native WINE is running while attempting to run patched binary wine

**Comment by Kreyren** [comment]
Blocked by https://github.com/Winetricks/winetricks/pull/1338 assuming that there is no way to make winetricks to invoke WINE after verb is called where function `winetricks_init()` is conflicting due to the:
https://github.com/Winetricks/winetricks/blob/f54242371e4917c94bfc01b87ea34727ad9ab09c/src/winetricks#L5106

**Comment by Kreyren** [comment]
New Issue: Riot Updater refuses wrapper libraries and is keep trying to repair itself if dgVoodoo2 to DXVK method is used.

image

**Comment by Kreyren** [comment]
The patches are now staged in wine-4.18 apparently, closing for the time being

**Pull request closed without merging**
