### PR TITLE
Add MS ole32 Module.

### PR DESCRIPTION
**Pull request by hillwoodroc**
Please add this module, Wechat need it.

### CODE REVIEW

**Comment by austin987** [comment]
Is there a bug upstream for this?

**Comment by hillwoodroc** [comment]
Yes, please view http://dldir1.qq.com/weixin/Windows/WeChatSetup.exe.

**Comment by austin987** [comment]
I meant a bug report on https://bugs.winehq.org

**Comment by hillwoodroc** [comment]
https://bugs.winehq.org/show_bug.cgi?id=42710 and https://bugs.winehq.org/show_bug.cgi?id=41908 , right?

**Comment by austin987** [comment]
Those are bugs, yes, but there's no indication in those bugs that native ole32 helps

**Comment by hillwoodroc** [comment]
OK, I added a comment about this. You can review https://bugs.winehq.org/show_bug.cgi?id=42710.

**Comment by austin987** [comment]
Thanks, committed

**Pull request merged**
