### PR TITLE
convert to sha256

### PR DESCRIPTION
**Pull request by vszakats**

### CODE REVIEW

**Comment by vszakats** [comment]
(Package names were formed from the filename part of the URL. I know it's not ideal, but it'd have been a much larger effort to look these up one-by-one from the `winetricks` source code.)

**Comment by austin987** [comment]
If you have those files in $WINTRICKS_CACHE, you can use convert_sha1_sha256.sh for that (it gets the commit prefix based on the package name in the cache)

**Comment by vszakats** [comment]
I believe I have nothing in my cache (not using winetricks at this moment on local machine.)
Let me resolve these conflicts in a few.

**Comment by vszakats** [comment]
Conflicts resolved.

**Comment by vszakats** [comment]
Closing this one, it will not be very useful with the conflict resolution in a common commit I think.

Here's the JSON with the updates:
```json
[
  {
    "url": "https://download.microsoft.com/download/9/e/5/9e5bfc66-a621-4e0d-8bfe-6688058c3f00/dxsdk_aug2006.exe",
    "sha1": "1e9cdbef391ebfbf781e6c87a375138d8c195c57",
    "sha256": "ab8d7d895089a88108d4148ef0f7e214b7a23c1ee9ba720feca78c7d4ca16c00"
  },
  {
    "url": "https://download.microsoft.com/download/A/E/7/AE743F1F-632B-4809-87A9-AA1BB3458E31/DXSDK_Jun10.exe",
    "sha1": "8fe98c00fde0f524760bb9021f438bd7d9304a69",
    "sha256": "11a0ddeb293040f8b99eeb1bdf6197ae1b26fdb74c036e5717d8e45db9c1576e"
  },
  {
    "url": "https://download.microsoft.com/download/F/9/4/F942F07D-F26F-4F30-B4E3-EBD54FABA377/NDP462-KB3151800-x86-x64-AllOS-ENU.exe",
    "sha1": "a70f856bda33d45ad0a8ad035f73092441715431",
    "sha256": "28886593e3b32f018241a4c0b745e564526dbb3295cb2635944e3a393f4278d4"
  },
  {
    "url": "https://download.microsoft.com/download/e/a/f/eafb8ee7-667d-4e30-bb39-4694b5b3006f/msxml6_x64.msi",
    "sha1": "ca0c0814a9c7024583edb997296aad7cb0a3cbf7",
    "sha256": "945d8c535758d5178d4de9063cfcba7dfa96987eaa478e0c03ba646cc7ca772f"
  },
  {
    "url": "https://download.microsoft.com/download/6/4/5/645FED5F-A6E7-44D9-9D10-FE83348796B0/wic_x64_enu.exe",
    "sha1": "4bdbf76a7bc96453306c893b4a7b2b8ae6127f67",
    "sha256": "5822fecd69a90c2833965a25e8779000825d69cc8c9250933f0ab70df52171e1"
  },
  {
    "url": "https://download.microsoft.com/download/5/9/1/5912526C-B950-4662-99B6-119A83E60E5C/xnafx31_redist.msi",
    "sha1": "bdd33b677c9576a63ff2a6f65e12c0563cc116e6",
    "sha256": "187e7e6b08fe35428d945612a7d258bfed25fad53cc54882983abdc73fe60f91"
  },
  {
    "url": "https://download.microsoft.com/download/E/6/7/E675FFFC-2A6D-4AB0-B3EB-27C9F8C8F696/PowerPointViewer.exe",
    "sha1": "ab48a8ebac88219c84f293c6c1e81f1a0f420da6",
    "sha256": "249473568eba7a1e4f95498acba594e0f42e6581add4dead70c1dfb908a09423"
  },
  {
    "url": "https://download.microsoft.com/download/a/1/8/a180e21e-9c2b-4b54-9c32-bf7fd7429970/EUupdate.EXE",
    "sha1": "9b076c40cb63aa0d8512aa8e610ba11d3466e441",
    "sha256": "464dd2cd5f09f489f9ac86ea7790b7b8548fc4e46d9f889b68d2cdce47e09ea8"
  },
  {
    "url": "https://launchpad.net/takao-fonts/trunk/003.02.01/+download/takao-fonts-ttf-003.02.01.zip",
    "sha1": "4f636d5c7c1bc16b96ea723adb16838cfb6df059",
    "sha256": "2f526a16c7931958f560697d494d8304949b3ce0aef246fb0c727fbbcc39089e"
  },
  {
    "url": "https://dl.google.com/picasa/picasa39-setup.exe",
    "sha1": "b3f7e2ee168811cb1d924eb34afe2b0d8153f89f",
    "sha256": "482c1a547d8d3aa25ee446d30ea986de63ef8c8d68b8d1109dd3d9b714e73e08"
  },
  {
    "url": "https://download.microsoft.com/download/A/6/A/A6AC035D-DA3F-4F0C-ADA4-37C8E5D34E3D/winsdk_web.exe",
    "sha1": "a8717ebb20a69c7efa85232bcb9899b8b07f98cf",
    "sha256": "9ea8d82a66a33946e8673df92d784971b35b8f65ade3e0325855be8490e3d51d"
  },
  {
    "url": "https://crayonphysicsdeluxe.s3.amazonaws.com/crayon_release52demo.exe",
    "sha1": "4ffd64c630f69e7cf024ef946c2c64c8c4ce4eac",
    "sha256": "3c221f4c4283d89c180337071b5d3f8b88b68cea0558e6f72abcb34ef954b923"
  },
  {
    "url": "https://lvlt.bioware.cdn.ea.com/bioware/u/f/eagames/bioware/dragonage2/demo/DragonAge2Demo_F93M2qCj_EnEsItPlRu.exe",
    "sha1": "a94715cd7943533a3cf1d84d40e667b04e1abc2e",
    "sha256": "615c014deed9b97de5662774fe25074862a7873c430d5d3650d07c7ce2727e9d"
  },
  {
    "url": "https://www.maxandthemagicmarker.com/maxdemo/max_demo_pc.zip",
    "sha1": "1a79c583ff40e7b2cf05d18a89a806fd6b88a5d1",
    "sha256": "6e2abd0cbd0ad04bfea9663402d7e9f24864d3f1c32df69eebf92dfc469fe6dd"
  }
]
```

**Comment by austin987** [comment]
Thanks, I've updated those verbs as well.

**Comment by vszakats** [comment]
Thank you!

**Pull request closed without merging**
