### PR TITLE
sound: restore verbs (from 50197be)

### LINKED ISSUE #1031: Missing sound verbs
It looks like the sound verbs were removed in the latest Winetricks release.  
The commit in which this change occured doesn't make it clear whether this was an intentional change or not: https://github.com/Winetricks/winetricks/commit/f5677f88a6d2fa1009a21f5feb582054cfb9fa07. I can't find any discussion related to this in issues/PRs neither.

Whether this was intentional or not, I think these verbs should stay. They are often used for debugging purposes, especially in programs where audio is crucial, such as in rhythm games. The `sound=alsa` verb is actually used by [one of the most popular guide to get osu! running on Linux](https://osu.ppy.sh/community/forums/topics/367783).

### PR DESCRIPTION
**Pull request by kakurasan**
Fixes #1031

### CODE REVIEW

**Comment by kakurasan** [comment]
@ThePooN This works for me. Could you test `https://raw.githubusercontent.com/kakurasan/winetricks/835f518fddac09e0dabcedcd10d0d6b2a1c8f28b/src/winetricks`? If it works for you, I guess this will be merged.

**Comment by kakurasan** [comment]
Travis job logs:
* [392272889 (Linux, sound=alsa, sound=pulse)](https://travis-ci.org/kakurasan/winetricks/jobs/392272889)
* [392272890 (macOS, sound=coreaudio)](https://travis-ci.org/kakurasan/winetricks/jobs/392272890)

**Comment by ThePooN** [comment]
yup, that works! thank you!

**Comment by austin987** [comment]
Thanks for beating me to it.

**Pull request merged**
