### PR TITLE
vcrun2019: update hashes

### PR DESCRIPTION
**Pull request by spannerman79**
vcrun2019: update hashes

### CODE REVIEW

**Review by gverm — CHANGES_REQUESTED** [review]
Please change the commit message to: "vcrun2019: update hash"

**Comment by spannerman79** [comment]
Done

**Review by gverm — APPROVED** [review]

**Comment by gombosg** [comment]
Just ran into this issue, the fix works fine. 👍🏽

**Comment by austin987** [comment]
Thanks @spannerman79 (and @gverm for reviewing)!

**Pull request merged**
