### PR TITLE
Add 64-bit support for ie8

### PR DESCRIPTION
**Pull request by qwertychouskie**
Experimental, so in as a separate verb.  Eventually will be merged with ie8.

### CODE REVIEW

**Comment by austin987** [comment]
Fails Travis

**Comment by qwertychouskie** [comment]
Fixed.

On 05/18/2017 04:40 PM, Austin English wrote:

Fails Travis

**Comment by austin987** [comment]
Sorry @qwertychouskie, thought I'd sent this earlier. I'm not a fan of making this a separate verb name, then deprecating it. I think you should only merge this when win64 is ready (and it should be within the same verb name, with if "$W_ARCH" as appropriate.

**Comment by qwertychouskie** [comment]
Sorry for the delay, I'll probaby work on this again once IE8 works in current Wine again.

**Comment by JamieMagee** [comment]
Apologies for digging up an old issue, but did you ever get a chance to look at this again @qwertychouskie? The reason I ask, is I think IE8 will help to solve [bug 46313](https://bugs.winehq.org/show_bug.cgi?id=46313).

**Pull request closed without merging**
