### PR TITLE
fix case change operations on/in case-insensitive filesystems/directories

### PR DESCRIPTION
**Pull request by openglfreak**

### CODE REVIEW

**Comment by austin987** [comment]
These should be separate commits prefixed with the verb, i.e. "protectionid: fix case change operations on/in case-insensitive filesystems/directories".

Did you find these with a script? If so, it would be helpful to add it to tests/winetricks-test so similar cases don't sneak in in the future.

**Comment by openglfreak** [comment]
I did not find them with a script, I just searched for `w_try mv` with the text editor.

**Comment by austin987** [comment]
I don't know that this is a common case worth fixing, but if you're so inclined, a generic could be made by introducing a w_try_mv() function, a la w_try_cd() to check for cases were only the case differs and handle it accordingly.

**Comment by openglfreak** [comment]
Should I do that?

**Comment by austin987** [comment]
I'm fine with the current changes, if you split the commits.

The suggestion would be a more permanent fix, but you don't have to do that. Up to you, I don't think this affects very many people 🙂

**Comment by openglfreak** [comment]
https://gist.github.com/openglfreak/14b505758b05a7cb7112265f77c17954
Would something like this be ok?

**Comment by openglfreak** [comment]
Meh, I'll leave it up to verb authors to not break something, just merge as-is for now

**Pull request merged**
