### PR TITLE
windows -> Windows

### PR DESCRIPTION
**Pull request by Faalagorn**
changed "windows" for uppercase "Windows" to match all other entries and allow sorting by title properly

### CODE REVIEW

**Comment by austin987** [comment]
Change is fine, but please use a better commit message (i.e. something like, "nt40: change 'windows' to 'Windows'")

**Comment by Faalagorn** [comment]
Thanks! I figured it would be easy to figure by looking at the files comparison, but on the other hand I guess there shouldn't be need to do so. Thank you for pointing that out, I'll keep that in mind for future :)

**Comment by cher-nov** [comment]
@Faalagorn, I believe, @austin987 meant that you could change commit message by `git commit --amend` and make then a force-push of `Faalagorn:patch-1`.

**Comment by austin987** [comment]
Yes, I did. Thanks for clarifying @cher-nov

**Pull request closed without merging**
