### PR TITLE
galliumnine{06,07}: new verb

### PR DESCRIPTION
**Pull request by dhewg**
And some additional broken markings for older versions

### CODE REVIEW

**Comment by dhewg** [comment]
Oh btw, I noticed that the ">= version" trailing comma for is missing in a few places

**Comment by dhewg** [comment]
ping

**Comment by austin987** [comment]
Hi @dhewg,

Sorry for the delay. I wanted to avoid merging anything using w_package_broken() until I fixed the recent regressions there.

The comma is not needed (it is used by w_wine_version_in(), which w_package_broken() is a wrapper around). My intention was to make an easier to understand wrapper, which the comma/syntax is confusing, but I fear I made it worse with the regression :/.

In any event, I've rebased your patch to remove those unneeded commas and pushed:
https://github.com/Winetricks/winetricks/commit/7b2b3c1d1441aeb250ed3960e49f6279db3bb502
https://github.com/Winetricks/winetricks/commit/3826a243b44603a035ed05fa76929a158005979b
https://github.com/Winetricks/winetricks/commit/1af3c79a9c3141560763628c038c66ad0c597f24

Thanks again!

**Comment by dhewg** [comment]
Nice, thanks!

**Pull request closed without merging**
