### PR TITLE
Update sha256 for adobeair (Issue #1158)

### PR DESCRIPTION
**Pull request by Kreyren**
Updated sha256 based on https://www.virustotal.com/#/file/24532d41ef2588c0daac4b6f8b7f863ee3c1a1b1e90b2d8d8b3eb4faa657e5e3/detection which is downloaded from https://airdownload.adobe.com/air/win/download/latest/AdobeAIRInstaller.exe (Line 5670 in src/winetricks)

### CODE REVIEW

**Comment by Kreyren** [comment]
@austin987  
image

**Comment by austin987** [comment]
@kreyren, I mean in winetricks. The line above where you changed has a list of previous installers. I'm asking you to add this one.

**Comment by Kreyren** [comment]
@austin987 Got it, sufficient?

**Comment by Chiitoo** [comment]
You'll want to 'squash' the commits so that there's only the one you first intended to push.

**Comment by austin987** [comment]
I don't think you meant to delete winetricks ;).

The commands you want are:
```
git rebase -i origin/master
# squash commits
git push -f
```

Also two minor things:
A: no need to mention virus total, follow the format above
B: you added some trailing whitespace, which is why Travis is complaining, please remove that.

Thanks for working on this!

**Comment by Kreyren** [comment]
recreating it

**Comment by Kreyren** [comment]
Created new Merge Request with requested changes https://github.com/Winetricks/winetricks/pull/1161

**Pull request closed without merging**
