### PR TITLE
WineD3D registry verbs overhaul

### PR DESCRIPTION
**Pull request by gverm**
This PR should make most, if not all, WineD3D registry verbs compliant again. I tried to add justifications where needed, but feel free to ask more info if needed.

### CODE REVIEW

**Comment by austin987** [comment]
```
In src/winetricks line 23022:
        glsl=disable*) w_call glsl=disabled ;;
        ^-----------^ SC2221: This pattern always overrides a later one on line 23072.
In src/winetricks line 23027:
        strictdrawordering=disable*) w_call strictdrawordering=disabled ;;
        ^-------------------------^ SC2221: This pattern always overrides a later one on line 23083.
In src/winetricks line 23034:
        *=disabled) w_do_call disabled "${cmd}";;
        ^--------^ SC2221: This pattern always overrides a later one on line 23072.
In src/winetricks line 23072:
        glsl=disabled) w_warn "Calling glsl=disabled is deprecated, please use shader_backend=arb instead" ; w_call shader_backend=arb ;;
        ^-----------^ SC2222: This pattern never matches because of a previous pattern on line 23022.
        ^-----------^ SC2222: This pattern never matches because of a previous pattern on line 23034.
In src/winetricks line 23083:
        strictdrawordering=disabled) w_warn "Calling strictdrawordering=disabled is deprecated, please use csmt=disabled instead" ; w_call csmt=disabled ;;
        ^-------------------------^ SC2222: This pattern never matches because of a previous pattern on line 23027.
        
        ```

**Comment by gverm** [comment]
@austin987 I added a commit to move up the compatibility hacks, which seems like the best solution to me.

**Comment by gverm** [comment]
@austin987 As requested on IRC, I dropped the first commit and rebased the rest.

**Comment by austin987** [comment]
Thanks!

**Pull request merged**
