### PR TITLE
maple_legends: new game

### PR DESCRIPTION
**Pull request by Kreyren**
Fixes https://github.com/Winetricks/winetricks/issues/1414

Made on demand originally created for MacOS

Signed-off-by: Jacob Hrbek <kreyren@rixotstudio.cz>

### CODE REVIEW

**Comment by Kreyren** [comment]
ping @tsujp : Please test

Referencing https://github.com/Winetricks/winetricks/wiki/How-to-make-a-side-fork in case you don't know how

**Comment by tsujp** [comment]
```
TODO: checksum
------------------------------------------------------
Executing mkdir -p /Users/tsujp/.cache/winetricks/maple_legends
Executing cd /Users/tsujp/.cache/winetricks/maple_legends
Downloading https://download2263.mediafire.com/hxuqc8n6ybzg/95v3yr38ym73667/MapleLegends2019Nov3Rev4.exe to /Users/tsujp/.cache/winetricks/maple_legends
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
100 27638    0 27638    0     0  12969      0 --:--:--  0:00:02 --:--:-- 12969
Executing cd /Users/tsujp
Executing wine /Users/tsujp/.cache/winetricks/maple_legends/MapleLegends2019Nov3Rev4.exe
wine: Bad EXE format for Y:\maple_legends\MapleLegends2019Nov3Rev4.exe.
------------------------------------------------------
Note: command wine /Users/tsujp/.cache/winetricks/maple_legends/MapleLegends2019Nov3Rev4.exe returned status 193. Aborting.
```

**Comment by tsujp** [comment]
Using that download link it seems to only want to download 25 KB of the .exe and then stop, hence the above error. If I put the full download (manually) into `/Users/tsujp/.cache/winetricks/maple_legends` and the error is:

```
warning: taskset/cpuset not available on your platform!
Using winetricks 20190912 - sha256sum: a251311a6490ce546f5c9b450492be26ae8099517cc3ed8c50d6ef065be4ad0d with wine-4.0.2 and WINEARCH=win32
Executing w_do_call maple_legends
Executing load_maple_legends 
------------------------------------------------------
TODO: checksum
------------------------------------------------------
Executing wine /Users/tsujp/.cache/winetricks/maple_legends/MapleLegends2019Nov3Rev4.exe
003c:fixme:process:SetProcessDEPPolicy (1): stub
0043:fixme:process:SetProcessDEPPolicy (1): stub
0043:fixme:win:DisableProcessWindowsGhosting : stub
0043:fixme:graphics:ShutdownBlockReasonDestroy (0x1007c): stub
0043:fixme:graphics:ShutdownBlockReasonCreate (0x1007c, L"Installing"): stub
0043:fixme:rstrtmgr:RmStartSession 0x49f3fc, 0, 0x49f400 stub!
0043:err:module:import_dll Library MFC42.DLL (which is needed by L"C:\\users\\tsujp\\Temp\\is-I070G.tmp\\isskin.dll") not found
```

A dialogue box also comes up

ERROR
Runtime Error (at: -1:0):
Cannot Import dll:C\users\tsujp\Temp\is-I070G.tmp\isskin.dll.

**Comment by tsujp** [comment]
Running from latest commit

```
warning: taskset/cpuset not available on your platform!
Using winetricks 20190912 - sha256sum: a251311a6490ce546f5c9b450492be26ae8099517cc3ed8c50d6ef065be4ad0d with wine-4.0.2 and WINEARCH=win32
Executing w_do_call maple_legends
Executing load_maple_legends 
./maple_legends.verb: line 18: w_debug: command not found
------------------------------------------------------
Outdated method used for platform detection, using compatibility wrapper from kreytricks
------------------------------------------------------
Executing cabextract -q -d /Users/tsujp/.wine/dosdevices/c:/windows/temp/_maple_legends -L -F i386/asms/60/msft/vcrtl/mfc42.dll /Users/tsujp/.cache/winetricks/winxpsp3/WindowsXP-KB936929-SP3-x86-ENU.exe
Executing cabextract -q --directory=/Users/tsujp/.wine/dosdevices/c:/windows/system32 /Users/tsujp/.wine/dosdevices/c:/windows/temp/_maple_legends/i386/asms/60/msft/vcrtl/mfc42.dll
/Users/tsujp/.wine/dosdevices/c:/windows/temp/_maple_legends/i386/asms/60/msft/vcrtl/mfc42.dll: no valid cabinets found
------------------------------------------------------
Note: command cabextract -q --directory=/Users/tsujp/.wine/dosdevices/c:/windows/system32 /Users/tsujp/.wine/dosdevices/c:/windows/temp/_maple_legends/i386/asms/60/msft/vcrtl/mfc42.dll returned status 1. Aborting.
------------------------------------------------------
```

**Comment by Kreyren** [comment]
uname -o is noted, will fix

**Comment by tsujp** [comment]
Same as before

```
warning: taskset/cpuset not available on your platform!
Using winetricks 20190912 - sha256sum: a251311a6490ce546f5c9b450492be26ae8099517cc3ed8c50d6ef065be4ad0d with wine-4.0.2 and WINEARCH=win32
Executing w_do_call maple_legends
Executing load_maple_legends 
File '/Users/tsujp/.cache/winetricks/maple_legends/MapleLegends2019Nov3Rev4.exe' is exported
------------------------------------------------------
Outdated method used for platform detection, using compatibility wrapper from kreytricks
------------------------------------------------------
Executing cabextract -q -d /Users/tsujp/.wine/dosdevices/c:/windows/temp/_maple_legends -L -F i386/asms/60/msft/vcrtl/mfc42.dll /Users/tsujp/.cache/winetricks/winxpsp3/WindowsXP-KB936929-SP3-x86-ENU.exe
Executing cabextract -q --directory=/Users/tsujp/.wine/dosdevices/c:/windows/system32 /Users/tsujp/.wine/dosdevices/c:/windows/temp/_maple_legends/i386/asms/60/msft/vcrtl/mfc42.dll
/Users/tsujp/.wine/dosdevices/c:/windows/temp/_maple_legends/i386/asms/60/msft/vcrtl/mfc42.dll: no valid cabinets found
------------------------------------------------------
Note: command cabextract -q --directory=/Users/tsujp/.wine/dosdevices/c:/windows/system32 /Users/tsujp/.wine/dosdevices/c:/windows/temp/_maple_legends/i386/asms/60/msft/vcrtl/mfc42.dll returned status 1. Aborting.
------------------------------------------------------
```

**Comment by tsujp** [comment]
```
warning: taskset/cpuset not available on your platform!
Using winetricks 20190912 - sha256sum: a251311a6490ce546f5c9b450492be26ae8099517cc3ed8c50d6ef065be4ad0d with wine-4.0.2 and WINEARCH=win32
Executing w_do_call maple_legends
Executing load_maple_legends 
File '/Users/tsujp/.cache/winetricks/maple_legends/MapleLegends2019Nov3Rev4.exe' is exported
------------------------------------------------------
Outdated method used for platform detection, using compatibility wrapper from kreytricks
------------------------------------------------------
Executing cabextract -q -d /Users/tsujp/.wine/dosdevices/c:/windows/temp/_maple_legends -L -F i386/asms/60/msft/vcrtl/mfc42.dll /Users/tsujp/.cache/winetricks/winxpsp3/WindowsXP-KB936929-SP3-x86-ENU.exe
Using native override for following DLLs: mfc42
Executing wine regedit C:\windows\Temp\_maple_legends\override-dll.reg
------------------------------------------------------
Winetricks was unable to extract mfc42.dll from winxpsp3
------------------------------------------------------
```

**Comment by tsujp** [comment]
Installer pops up log from terminal is

```
Executing wine /Users/tsujp/.cache/winetricks/maple_legends/MapleLegends2019Nov3Rev4.exe
0038:fixme:process:SetProcessDEPPolicy (1): stub
003a:fixme:process:SetProcessDEPPolicy (1): stub
003a:fixme:win:DisableProcessWindowsGhosting : stub
003a:fixme:graphics:ShutdownBlockReasonDestroy (0x1007c): stub
003a:fixme:graphics:ShutdownBlockReasonCreate (0x1007c, L"Installing"): stub
003a:fixme:rstrtmgr:RmStartSession 0x49f3fc, 0, 0x49f400 stub!
003a:fixme:graphics:ShutdownBlockReasonDestroy (0x1007c): stub
003a:fixme:graphics:ShutdownBlockReasonCreate (0x1007c, L"Installing MapleLegends."): stub
003a:fixme:msg:ChangeWindowMessageFilterEx 0x1008e c046 1 0x0
003a:fixme:msg:ChangeWindowMessageFilterEx 0x10096 c046 1 0x0
003a:fixme:msg:ChangeWindowMessageFilterEx 0x20096 c046 1 0x0
003a:fixme:shell:SHAutoComplete stub
```

**Comment by Kreyren** [comment]
> in it's installed directory

What is the installed directory?

> Now hangs forever. 

Is wine running as a process?

**Comment by tsujp** [comment]
> > in it's installed directory
> 
> What is the installed directory?

C:\MapleLegendsHD

Attempting to run `MapleLegends.exe` after changing to that directory.

> > Now hangs forever.
> 
> Is wine running as a process?

It appears to be as `/usr/local/Cellar/wine/4.0.2/lib/../bin/wine-preloader MapleLegends.exe ` is in my `ps aux | grep wine` list

```
/usr/local/Cellar/wine/4.0.2/lib/../bin/wineserver
/usr/local/Cellar/wine/4.0.2/lib64/../bin/wine64-preloader C:\windows\system32\services.exe 
/usr/local/Cellar/wine/4.0.2/lib64/../bin/wine64-preloader C:\windows\system32\winedevice.exe 
/usr/local/Cellar/wine/4.0.2/lib64/../bin/wine64-preloader C:\windows\system32\plugplay.exe 
/usr/local/Cellar/wine/4.0.2/lib64/../bin/wine64-preloader C:\windows\system32\winedevice.exe 
/usr/local/Cellar/wine/4.0.2/lib/../bin/wine-preloader MapleLegends.exe 
/usr/local/Cellar/wine/4.0.2/lib64/../bin/wine64-preloader C:\windows\system32\explorer.exe /desktop 
```

**Comment by Kreyren** [comment]
> -rwxrwxrwx  1 tsujp staff 115K Nov  4 17:05 d3d9.dll*

Might be related

try invoking `winetricks d3dx9_43`

**Comment by tsujp** [comment]
Killing it with `SIGKILL` and relaunching again does the same thing, hanging forever.

**Comment by tsujp** [comment]
I believe swapping to win98 from win7 also helps here for some reason

**Comment by Kreyren** [comment]
> I believe swapping to win98 from win7 also helps here for some reason

Noted, but do not perform that now, lets try the directX 9 libs first

**Comment by tsujp** [comment]
After `winetricks d3dx9_43`, received

```
preloader: Warning: failed to reserve range 000000007ff00000-000000007fff0000
wine: failed to map the shared user data: c0000018
000b:err:wineboot:ProcessRunKeys Error running cmd L"C:\\windows\\system32\\winemenubuilder.exe -a -r" (1359)
0009:fixme:toolhelp:CreateToolhelp32Snapshot Unimplemented: heap list snapshot
0050:fixme:ntdll:NtQueryInformationToken QueryInformationToken( ..., TokenElevation, ...) semi-stub
0050:fixme:dwmapi:DwmGetCompositionTimingInfo (0x0 0x2c0fdd4)
```

**Comment by tsujp** [comment]
Very long debug from `winetricks -vv maple_legends`

```
+ winetricks_metadata_exists maple_legends
+ test -f '/var/folders/0r/g5ply65j0dxg7xqx5fyymkcc0000gn/T//winetricks.ef3yi3VC/w.tsujp.19146/metadata/*/maple_legends.vars'
+ _W_md_cmd=maple_legends
+ _W_category=games
+ file=/var/folders/0r/g5ply65j0dxg7xqx5fyymkcc0000gn/T//winetricks.ef3yi3VC/w.tsujp.19146/metadata/games/maple_legends.vars
+ shift
+ shift
+ for arg in '"$@"'
+ case "$arg" in
+ echo 'title="Maple Legends"'
+ for arg in '"$@"'
+ case "$arg" in
+ echo 'publisher="Microsoft"'
+ for arg in '"$@"'
+ case "$arg" in
+ echo 'year="2006"'
+ for arg in '"$@"'
+ case "$arg" in
+ echo 'media="manual_download"'
+ for arg in '"$@"'
+ case "$arg" in
+ echo 'file1="MapleLegends2019Nov3Rev4.exe"'
+ for arg in '"$@"'
+ case "$arg" in
+ w_die 'bug: w_metadata maple_legends has a unix path for installed_exe1, should be a windows path'
+ w_warn 'bug: w_metadata maple_legends has a unix path for installed_exe1, should be a windows path'
+ '[' -z '' ']'
+ echo ------------------------------------------------------
+ echo 'bug: w_metadata maple_legends has a unix path for installed_exe1, should be a windows path'
+ echo ------------------------------------------------------
+ test ''
+ case $WINETRICKS_GUI in
+ unset _W_timeout
+ exit 1
+ winetricks_cleanup
+ test ''
+ set +e
+ test -f /var/folders/0r/g5ply65j0dxg7xqx5fyymkcc0000gn/T//winetricks.ef3yi3VC/w.tsujp.19146/dd-pid
+ test /Users/tsujp/.wine/dosdevices/y:
+ rm -f /Users/tsujp/.wine/dosdevices/y:
+ test '' = 1
+ rm -rf /var/folders/0r/g5ply65j0dxg7xqx5fyymkcc0000gn/T//winetricks.ef3yi3VC/w.tsujp.19146
+ test '' = 1
+ rm -rf /var/folders/0r/g5ply65j0dxg7xqx5fyymkcc0000gn/T//winetricks.ef3yi3VC
```

**Comment by Kreyren** [comment]
> + echo 'bug: w_metadata maple_legends has a unix path for installed_exe1, should be a windows path'

There is the issue.. weird that winetricks doesn't output this

**Comment by Kreyren** [comment]
Requires following for runtime:
```
kreyren@dreamon:~$ wine ~/.wine/drive_c/MapleLegendsHD/MapleLegends.exe 
0097:err:module:import_dll Library ijl15.dll (which is needed by L"C:\\MapleLegendsHD\\MapleLegends.exe") not found
0097:err:module:import_dll Library npkcrypt.dll (which is needed by L"C:\\MapleLegendsHD\\MapleLegends.exe") not found
0097:err:module:import_dll Library wzmss.dll (which is needed by L"C:\\MapleLegendsHD\\MapleLegends.exe") not found
0097:err:module:LdrInitializeThunk Importing dlls for L"C:\\MapleLegendsHD\\MapleLegends.exe" failed, status c0000135
```

**Comment by Kreyren** [comment]
Requires MFC42.DLL for installer

```
Executing wine /home/kreyren/.cache/winetricks/maple_legends/MapleLegends2019Nov3Rev4.exe
006b:err:module:import_dll Library MFC42.DLL (which is needed by L"C:\\users\\kreyren\\Temp\\is-GEN08.tmp\\isskin.dll") not found
```

**Comment by Kreyren** [comment]
Kept as legacy

```bash
# Following libs are required for runtime (https://github.com/Winetricks/winetricks/pull/1415#issuecomment-550009610)
					## Ijl15.dll - "Intel® JPEG Library - Retail Version"
					if [ ! -e "$W_SYSTEM32_DLLS/ijl15.dll" ]; then
							# Download from mirror
							w_download_to "$W_PACKAGE" http://www.dlldownloader.com/ijl11-dll/download/dbe77131a44577889e099c8d10ae6766/2ac2b6aac85d6ec7c899727350383429/ e631ec21260b6d02423f75240050ff17b45cdb090c9073f5a704d64d3dbbff48 ijl11.dll.zip

							# Extract the file from mirror
							if [ -e "$W_CACHE/$W_PACKAGE/ijl11.dll.zip" ]; then
									w_try_unzip "$W_TMP" "$W_CACHE/$W_PACKAGE/ijl11.dll.zip" "ijl11.dll"
									if [ -e "$W_TEMP/ijl11.dll" ]; then
											w_try cp "$W_TEMP/ijl11.dll" "$W_SYSTEM32_DLLS"
											# Self-check
											if [ ! -e "$W_SYSTEM32_DLLS/ijl11.dll" ]; then
													w_die "File '$W_SYSTEM32_DLLS/ijl11.dll' was not extracted which is required for runtime of maple legends"
											elif [ -e "$W_SYSTEM32_DLLS/ijl11.dll" ]; then
													w_debug "File '$W_SYSTEM32_DLLS/ijl11.dll' has been extracted successfully"
											fi
									elif [ ! -e "$W_TMP/ijl11.dll" ]; then
											w_die "File '$W_TMP/ijl11.dll' does not exists, which is required for runtime of maple legends"
									fi
								elif [ ! -e "$W_CACHE/$W_PACKAGE/ijl11.dll.zip" ]; then
										w_die "File '$W_CACHE/$W_PACKAGE/ijl11.dll.zip' does not exists, unable to extract required library for runtime of maple legends"
								fi

								# Make sure that it's being used
								w_override_dlls native ijl11
					elif [ -e "$W_SYSTEM32_DLLS/ijl15.dll" ]; then
							w_debug "File '$W_SYSTEM32_DLLS/ijl15.dll' already exists, no need to extract it"
					fi
```

i've made logic for wrong thing

**Comment by Kreyren** [comment]
Kept as legacy

```sh
              # Export mfc42.dll from winxpsp3
              # helper_winxpsp3 i386/asms/60/msft/vcrtl/mfc42.dll
              # if [ -e "$W_TMP/i386/asms/60/msft/vcrtl/mfc42.dll" ]; then
              #     w_try cp "$W_TMP/i386/asms/60/msft/vcrtl/mfc42.dll" "$W_SYSTEM32_DLLS"
              # elif [ ! -e "$W_TMP/i386/asms/60/msft/vcrtl/mfc42.dll" ]; then
              #     w_die "Expected file '$W_TMP/i386/asms/60/msft/vcrtl/mfc42.dll' is not present to be exported in '$W_SYSTEM32_DLLS'"
              # fi
              # w_override_dlls native mfc42
```

Using `mfc42` verb is better

**Comment by Kreyren** [comment]
if `npkcrypt.dll` is exported it also depends on `npkpdb.dll`

```
kreyren@dreamon:~/.wine/drive_c/windows/syswow64$ wine ~/.wine/drive_c/MapleLegendsHD/MapleLegends.exe 
002e:err:module:import_dll Library npkpdb.dll (which is needed by L"C:\\windows\\system32\\npkcrypt.dll") not found
002e:err:module:import_dll Library npkcrypt.dll (which is needed by L"C:\\MapleLegendsHD\\MapleLegends.exe") not found
002e:err:module:import_dll Library wzmss.dll (which is needed by L"C:\\MapleLegendsHD\\MapleLegends.exe") not found
002e:err:module:LdrInitializeThunk Importing dlls for L"C:\\MapleLegendsHD\\MapleLegends.exe" failed, status c0000135
```

**Comment by Kreyren** [comment]
Transfered in https://github.com/Kreytricks/kreytricks/pull/15

Will be re-made in winetricks once it's working

**Pull request closed without merging**
