### PR TITLE
rockstar_games_launcher: New app

### PR DESCRIPTION
**Pull request by Klairm**
Do not merge pls

### CODE REVIEW

**Comment by Kreyren** [comment]
### MAINTAINERS NOTICE

I'm mentoring @Klairm on his request with the intention to contribute rockstar launcher in winetricks, Do not merge until approved.

**Comment by Kreyren** [comment]
For some reason you are changing 37 files with no changes which is unexpected.

Expecting to change only `src/winetricks`

**Comment by Klairm** [comment]
Actual error :
<script src="https://gist.github.com/Klairm/4761cba4548c6f823d7bde251cfeb086.js"></script>

**Comment by Kreyren** [comment]
> The actual error for the app is comdlg32.dll missing based on this log:
> https://gist.github.com/Klairm/4761cba4548c6f823d7bde251cfeb086
> 
> Working on a fix


Since i don't want to give you the solution so that you would learn how to resolve these issues by yourself i'm giving you a recommendation to fix this:

1) Google/DuckDuckGo
2) Trying to extract it from some M$ provided cabinet file (for example we can use cabextract on https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads to get the dlls provided with the installation example usage on https://github.com/Winetricks/winetricks/pull/1411/files )
3) Asking in #winehackers or #winehq on freenode

**Comment by austin987** [comment]
Please don't send drafts here. My inbox is not the place for your initial development.

**Comment by Kreyren** [comment]
@austin987 i encouraged it.. 

Are you getting an email per new message in here or? Since i believe that this kind of development is beneficial

**Pull request closed without merging**
