### PR TITLE
Change strings to proper case, wine to Wine, etc

### PR DESCRIPTION
**Pull request by vanillajonathan**

### CODE REVIEW

**Comment by austin987** [comment]
Was this done with a script or manually?

Please use better commit messages, this applies to your other PRs as well.

**Comment by vanillajonathan** [comment]
This was done manually.

**Comment by austin987** [comment]
On May 6, 2016 4:41 AM, "Jonathan" <notifications@github.com> wrote:
>
> This was done manually.

I ask because the results are inconsistent, e.g. some instances of 'wine'
are not capitalized while others are

I'm also not sure about some of the corrections, e.g. command line and
command-line instead of one spelling.

Lastly,  as I said before "Update x" is not a good changelog. Please use
better ones when updating the pull request.

**Comment by vanillajonathan** [comment]
I may have missed some occurrences hence it being inconsistent. Or it being so because some references are referencing the name of the software while others are referencing the name of the executable.

I believe proper usage to be "command line" as these are two words, not one. But "command-line mode" with a hyphen as per the title on Wikipedia.
https://en.wikipedia.org/wiki/Command-line_interface
However it should probably be "command-line interface" in those places it currently states "command line" or "commandline".

**Comment by qwertychouskie** [comment]
Looks good to me.  Any reason this has net been merged yet?

**Comment by austin987** [comment]
I hadn't received a notification for it (github only notifies for comments, not new/edited commits).

I'll review when I have time. Please squash commits rather than add more though.

**Comment by vanillajonathan** [comment]
"Only those with write access to this repository can merge pull requests.".

Not sure how or if I can perform a merge.

**Comment by austin987** [comment]
git rebase -i origin/master
then use squash/s to combine the commits
Finally, git push --force

**Comment by vanillajonathan** [comment]
I use GitHub via the website, not via the Git software.
Also my repository has since been deleted.

**Comment by austin987** [comment]
https://github.com/Winetricks/winetricks/commit/97a23b031c7a8eef857be2536fa49908e4c05747

It would be useful to learn the git commands, as the GUI doesn't allow that feature, unfortunately. It's slower for me to review and have to merge/edit manually, that's why I'd prefer it ready to go, essentially I need the commits ready to go as-is.

**Pull request closed without merging**
