### PR TITLE
switch to secure URL alternatives, where available

### PR DESCRIPTION
**Pull request by vszakats**

### CODE REVIEW

**Comment by vszakats** [comment]
I used a script to discover secure URLs that return the same result as the existing ones.
Those that didn't fully match were all verified manually in a browser, with redirects followed as necessary. This same script/method was used upgrade most URLs in Homebrew and Homebrew Cask.

**Comment by austin987** [comment]
Thanks. Could you share the script?

--
-Austin
GPG: 14FB D7EA A041 937B

**Comment by vszakats** [comment]
@austin987 A gentle heads up: It's written in a very obscure language and it's a rather messy/rough source. There you go: https://gist.github.com/vszakats/7bdb547e367338299d029140fd8208ed

**Comment by vszakats** [comment]
(the original pure shell script edition was not enough/practical after a point.)

**Comment by vszakats** [comment]
Is there interest in getting this merged? Anything that might be missing before doing so?

**Comment by austin987** [comment]
Yes, there is. I have several other bugs I want to fix first, as I'll need to do a working make test before I can test/merge this. Sorry, I should've said something before.

But anything that improves encryption/security gets+1 from me :)

**Comment by vszakats** [comment]
Cool, thanks and agreed on the test! Let me know if anything comes up that I can update/fix.

**Comment by vszakats** [comment]
One more thought regarding security: I think it'd be nice to replace SHA1 checksums with SHA256 ones.

I've written a bash script for that for `PKGBUILD` packages (used in MSYS2 and Arch Linux): https://gist.github.com/vszakats/ddd9be9631bfe2ee33af (details are different, but the idea is the same)

**Comment by vszakats** [comment]
@austin987 I've rewritten the script from scratch in bash. Maybe you'll find it useful: https://github.com/vszakats/https-check/blob/master/chkhttps.sh

**Comment by austin987** [comment]
Thanks @vszakats.

I also filed a bug to remind myself to switch to sha256. You can follow it here #737

**Comment by vszakats** [comment]
Resolved conflicts.

**Comment by vszakats** [comment]
Any chance to have this merged?

**Comment by vszakats** [comment]
Apparently not much. Closing.

**Comment by austin987** [comment]
@vszakats I do intend to, I'm sorry for the delays. I've been busy with real life and wanted to get winetricks-test passing first.

I expect to look at this this week, likely tonight or tomorrow.

**Comment by vszakats** [comment]
Thank you @austin987. Sorry for being impatient, but the patch is large and quickly becomes conflicted. Let me know if I may help in any way.

**Comment by austin987** [comment]
@vszakats sure, I understand. FWIW, given the delay I caused, I woud've done the rebasing for you ;)

**Comment by vszakats** [comment]
No worries, it was an easy one :) Though I'll need to fix it to use `$WINETRICKS_SOURCEFORGE`.

**Comment by vszakats** [comment]
Ok, done. (I swapped the ftp:// address to an original sf.net URL. Last month sf.net [switched](https://sourceforge.net/blog/small-but-significant-changes-to-project-pages/) all its mirrors to use HTTPS, which is good.)

**Comment by austin987** [comment]
This breaks linkcheck.sh:
BAD https://repacks.net/uploads/dotNetFx462_Full_x86_x64_Slim.exe
curl: (51) SSL: no alternative certificate subject name matches target host name 'repacks.net'

Loading that in Firefox shows:
repacks.net uses an invalid security certificate. The certificate is only valid for mail.repacks.net Error code: SSL_ERROR_BAD_CERT_DOMAIN

(this is an FYI, I'll fix it on my end)

**Comment by vszakats** [comment]
Seem like they issued a new certificate a few days ago, with the `CN` wrongly set.
```
* Server certificate:
*  subject: CN=mail.repacks.net
*  start date: Feb  8 00:00:00 2017 GMT
*  expire date: May  9 23:59:59 2017 GMT
*  subjectAltName does not match repacks.net
* SSL: no alternative certificate subject name matches target host name 'repacks.net'
```

**Comment by vszakats** [comment]
`https://repacks.net/forum/viewtopic.php?t=7` also needs to be reverted.

**Comment by austin987** [comment]
Of course.

**Comment by austin987** [comment]
(Finally) merged as https://github.com/Winetricks/winetricks/commit/b7b7d12486b0f2fc96f065bd0b096f96d2ce72a2

Thanks again for the patch, I really like increasing security / encryption where possible. Again sorry it took so long.

**Comment by vszakats** [comment]
No problem at all, thank you very much for the double-check and the merge of course.

**Pull request closed without merging**
