### PR TITLE
upgrade hash to sha256 for secure downloads

### PR DESCRIPTION
**Pull request by vszakats**
Where original sha1 matched the download.
Downloads were done using this command: `curl -fsS -L --proto-redir =https '<url>' -o bin.bin`

### CODE REVIEW

**Comment by vszakats** [comment]
Here's the JSON describing the updates:
```json
[
  {
    "url": "https://airdownload.adobe.com/air/win/download/20.0/AdobeAIRInstaller.exe",
    "sha1": "2fdd561556fe881c4e5538d4ee37f523871befd3",
    "sha256": "318770b9a18e59ca4a721a1f5c2b0235cffdbe77a043e99cb2af32074d61de45"
  },
  {
    "url": "https://download.microsoft.com/download/D/2/A/D2A2FC8B-0447-491C-A5EF-E8AA3A74FB98/AccessRuntime.exe",
    "sha1": "571811b7536e97cf4e4e53bbf8260cddd69f9b2d",
    "sha256": "a00a92fdc4ddc0dcf5d1964214a8d7e4c61bb036908a4b43b3700063eda9f4fb"
  },
  {
    "url": "https://download.microsoft.com/download/3/a/5/3a5925ac-e779-4b1c-bb01-af67dc2f96fc/VisualBasic6-KB896559-v1-ENU.exe",
    "sha1": "f52cf2034488235b37a1da837d1c40eb2a1bad84",
    "sha256": "c4d43fe4aea782d7d6c08c038778fe3635c7bae1b93fb1a7740c6644aabf567e"
  },
  {
    "url": "https://download.microsoft.com/download/9/e/5/9e5bfc66-a621-4e0d-8bfe-6688058c3f00/dxsdk_aug2006.exe",
    "sha1": "1e9cdbef391ebfbf781e6c87a375138d8c195c57",
    "sha256": "ab8d7d895089a88108d4148ef0f7e214b7a23c1ee9ba720feca78c7d4ca16c00"
  },
  {
    "url": "https://download.microsoft.com/download/A/E/7/AE743F1F-632B-4809-87A9-AA1BB3458E31/DXSDK_Jun10.exe",
    "sha1": "8fe98c00fde0f524760bb9021f438bd7d9304a69",
    "sha256": "11a0ddeb293040f8b99eeb1bdf6197ae1b26fdb74c036e5717d8e45db9c1576e"
  },
  {
    "url": "https://download.microsoft.com/download/a/a/c/aac39226-8825-44ce-90e3-bf8203e74006/dotnetfx.exe",
    "sha1": "16a354a2207c4c8846b617cbc78f7b7c1856340e",
    "sha256": "ba0e58ec93f2ffd54fc7c627eeca9502e11ab3c6fc85dcbeff113bd61d995bce"
  },
  {
    "url": "https://download.microsoft.com/download/8/b/4/8b4addd8-e957-4dea-bdb8-c4e00af5b94b/NDP1.1sp1-KB867460-X86.exe",
    "sha1": "74a5b25d65a70b8ecd6a9c301a0aea10d8483a23",
    "sha256": "2c0a35409ff0873cfa28b70b8224e9aca2362241c1f0ed6f622fef8d4722fd9a"
  },
  {
    "url": "https://download.lenovo.com/ibmdl/pub/pc/pccbbs/thinkvantage_en/dotnetfx.exe",
    "sha1": "a3625c59d7a2995fb60877b5f5324892a1693b2a",
    "sha256": "46693d9b74d12454d117cc61ff2e9481cabb100b4d74eb5367d3cf88b89a0e71"
  },
  {
    "url": "https://download.microsoft.com/download/c/4/b/c4b15d7d-6f37-4d5a-b9c6-8f07e7d46635/setup.exe",
    "sha1": "4e4b1072b5e65e855358e2028403f2dc52a62ab4",
    "sha256": "1d7337bfbb2c65f43c82d188688ce152af403bcb67a2cc2a3cc68a580ecd8200"
  },
  {
    "url": "https://download.microsoft.com/download/0/8/c/08c19fa4-4c4f-4ffb-9d6c-150906578c9e/NetFx20SP1_x86.exe",
    "sha1": "eef5a36924cdf0c02598ccf96aa4f60887a49840",
    "sha256": "c36c3a1d074de32d53f371c665243196a7608652a2fc6be9520312d5ce560871"
  },
  {
    "url": "https://download.microsoft.com/download/c/6/e/c6e88215-0178-4c6c-b5f3-158ff77b1f38/NetFx20SP2_x86.exe",
    "sha1": "22d776d4d204863105a5db99e8b8888be23c61a7",
    "sha256": "6e3f363366e7d0219b7cb269625a75d410a5c80d763cc3d73cf20841084e851f"
  },
  {
    "url": "https://download.microsoft.com/download/8/F/E/8FEEE89D-9E4F-4BA3-993E-0FFEA8E21E1B/NetFx30SP1_x86.exe",
    "sha1": "8d779e337920b097aa0c01859912950606e9fc12",
    "sha256": "3100df4d4db3965ead9520c887a534115cf6fc7ba100abde45226958b865695b"
  },
  {
    "url": "https://download.microsoft.com/download/2/5/2/2526f55d-32bc-410f-be18-164ba67ae07d/XPSEP%20XP%20and%20Server%202003%2032%20bit.msi",
    "sha1": "5d332ebd1025e294adafe72030fe33db707b2c82",
    "sha256": "630c86a202c40cbcd430701977d4f1fefa6151624ef9a4870040dff45e547dea"
  },
  {
    "url": "https://download.microsoft.com/download/6/0/f/60fc5854-3cb8-4892-b6db-bd4f42510f28/dotnetfx35.exe",
    "sha1": "0a271bb44531aadef902829f98dfad66e4a57586",
    "sha256": "3e3a4104bad9a0c270ed5cbe8abb986de9afaf0281a98998bdbdc8eaab85c3b6"
  },
  {
    "url": "https://download.microsoft.com/download/2/0/e/20e90413-712f-438c-988e-fdaa79a8ac3d/dotnetfx35.exe",
    "sha1": "3dce66bae0dd71284ac7a971baed07030a186918",
    "sha256": "0582515bde321e072f8673e829e175ed2e7a53e803127c50253af76528e66bc1"
  },
  {
    "url": "https://download.microsoft.com/download/9/5/A/95A9616B-7A37-4AF6-BC36-D6EA96C8DAAE/dotNetFx40_Full_x86_x64.exe",
    "sha1": "58da3d74db353aad03588cbb5cea8234166d8b99",
    "sha256": "65e064258f2e418816b304f646ff9e87af101e4c9552ab064bb74d281c38659f"
  },
  {
    "url": "https://download.microsoft.com/download/b/a/4/ba4a7e71-2906-4b2d-a0e1-80cf16844f5f/dotnetfx45_full_x86_x64.exe",
    "sha1": "b2ff712ca0947040ca0b8e9bd7436a3c3524bb5d",
    "sha256": "a04d40e217b97326d46117d961ec4eda455e087b90637cb33dd6cc4a2c228d83"
  },
  {
    "url": "https://download.microsoft.com/download/E/2/1/E21644B5-2DF2-47C2-91BD-63C560427900/NDP452-KB2901907-x86-x64-AllOS-ENU.exe",
    "sha1": "89f86f9522dc7a8a965facce839abb790a285a63",
    "sha256": "6c2c589132e830a185c5f40f82042bee3022e721a216680bd9b3995ba86f3781"
  },
  {
    "url": "https://download.microsoft.com/download/C/3/A/C3A5200B-D33C-47E9-9D70-2F7C65DAAD94/NDP46-KB3045557-x86-x64-AllOS-ENU.exe",
    "sha1": "3049a85843eaf65e89e2336d5fe6e85e416797be",
    "sha256": "b21d33135e67e3486b154b11f7961d8e1cfd7a603267fb60febb4a6feab5cf87"
  },
  {
    "url": "https://download.microsoft.com/download/E/4/1/E4173890-A24A-4936-9FC9-AF930FE3FA40/NDP461-KB3102436-x86-x64-AllOS-ENU.exe",
    "sha1": "83d048d171ff44a3cad9b422137656f585295866",
    "sha256": "beaa901e07347d056efe04e8961d5546c7518fab9246892178505a7ba631c301"
  },
  {
    "url": "https://download.microsoft.com/download/F/9/4/F942F07D-F26F-4F30-B4E3-EBD54FABA377/NDP462-KB3151800-x86-x64-AllOS-ENU.exe",
    "sha1": "a70f856bda33d45ad0a8ad035f73092441715431",
    "sha256": "28886593e3b32f018241a4c0b745e564526dbb3295cb2635944e3a393f4278d4"
  },
  {
    "url": "https://msdnshared.blob.core.windows.net/media/2016/10/netfx_setupverifier_new.zip",
    "sha1": "6eef0158dc637d186d4ab5eb13aee6ef577831b2",
    "sha256": "1daf4b1b27669b65f613e17814da3c8342d3bfa9520a65a880c58d6a2a6e32b5"
  },
  {
    "url": "https://download.microsoft.com/download/5/5/8/55846E20-4A46-4EF8-B272-7F988BC9090A/gfwlivesetupmin.exe",
    "sha1": "6f9e0ba052c68c8b51bb0e3ce6024d0e1c7b20b2",
    "sha256": "b14609508e2f8dba0886ded84e2817ad532ebfa31f8a6d4be2e6a5a03a9d7c23"
  },
  {
    "url": "https://download.microsoft.com/download/4/3/9/4393c9ac-e69e-458d-9f6d-2fe191c51469/jet40sp8_9xnt.exe",
    "sha1": "8cd25342030857969ede2d8fcc34f3f7bcc2d6d4",
    "sha256": "b060246cd499085a31f15873689d5fa7df817e407c8261a5c71fa6b9f7042560"
  },
  {
    "url": "https://download.microsoft.com/download/3/8/C/38CE0ABB-01FD-4C0A-A569-BC5E82C34A17/IE8-WindowsXP-KB2936068-x86-ENU.exe",
    "sha1": "1bdeb741085b8f1ef6efc83f8615121373107347",
    "sha256": "8bda23c78cdcd9d01c364a01c6d639dfb2d11550a5521b8a81c808c1a2b1824e"
  },
  {
    "url": "https://download.microsoft.com/download/4/a/a/4aafff19-9d21-4d35-ae81-02c48dcbbbff/MDAC_TYP.EXE",
    "sha1": "4fbc272c79da59e38818924d8575accb0af776fb",
    "sha256": "157ebae46932cb9047b58aa849ac1885e8cbd2f218810cb83e57613b49c679d6"
  },
  {
    "url": "https://ftp.mozilla.org/pub/mozilla.org/mozilla/libraries/win32/MozillaBuildSetup-2.0.0.exe",
    "sha1": "daba4bc03ae9014c68611fd36b05dcc4083c6fdb",
    "sha256": "d5ffe52fe634fb7ed02e61041cc183c3af92039ee74e794f7ae83a408e4cf3f5"
  },
  {
    "url": "https://download.microsoft.com/download/A/2/D/A2D8587D-0027-4217-9DAD-38AFDB0A177E/msxml.msi",
    "sha1": "aa70c5c1a7a069af824947bcda1d9893a895318b",
    "sha256": "47c2ae679c37815da9267c81fc3777de900ad2551c11c19c2840938b346d70bb"
  },
  {
    "url": "https://download.microsoft.com/download/e/a/f/eafb8ee7-667d-4e30-bb39-4694b5b3006f/msxml6_x64.msi",
    "sha1": "ca0c0814a9c7024583edb997296aad7cb0a3cbf7",
    "sha256": "945d8c535758d5178d4de9063cfcba7dfa96987eaa478e0c03ba646cc7ca772f"
  },
  {
    "url": "https://download.microsoft.com/download/e/a/f/eafb8ee7-667d-4e30-bb39-4694b5b3006f/msxml6_x86.msi",
    "sha1": "5125220e985b33c946bbf9f60e2b222c7570bfa2",
    "sha256": "efa48f8cab5a89b8e667ed3e10dfb71bddc02923d0f3757bd93ffabe6fb6c598"
  },
  {
    "url": "https://uk.download.nvidia.com/Windows/9.14.0702/PhysX-9.14.0702-SystemSoftware.msi",
    "sha1": "81e2d38e2356e807ad80cdf150ed5acfff839c8b",
    "sha256": "0a022e28accf5851be9d6577487cdcd3d3a3e2a8a21a64456b72b415c217f03c"
  },
  {
    "url": "https://www.libsdl.org/release/SDL-1.2.14-win32.zip",
    "sha1": "d22c71d1c2bdf283548187c4b0bd7ef9d0c1fb23",
    "sha256": "ce77838902891bf2e4378d4a910afef88aaaae4f833a49cfc9bb8dde11ff89a7"
  },
  {
    "url": "https://download.microsoft.com/download/B/4/3/B4314928-7B71-4336-9DE7-6FA4CF00B7B3/SpeechSDK51.exe",
    "sha1": "f69efaee8eb47f8c7863693e8b8265a3c12c4f51",
    "sha256": "520aa5d1a72dc6f41dc9b8b88603228ffd5d5d6f696224fc237ec4828fe7f6e0"
  },
  {
    "url": "https://www.conradshome.com/win31/archive/softlib/vbrun200.exe",
    "sha1": "ac0568b73ee375408778e9b505df995f79ab907e",
    "sha256": "4b0811d8fdcac1fd9411786c9119dc8d98d0540948211bdbc1ac682fbe5c0228"
  },
  {
    "url": "https://download.microsoft.com/download/vb30/utility/1/w9xnt4/en-us/vb3run.exe",
    "sha1": "518fcfefde9bf680695cadd06512efadc5ac2aa7",
    "sha256": "3ca3ad6332f83b5c2b86e4758afa400150f07ae66ce8b850d8f9d6bcd47ad4cd"
  },
  {
    "url": "https://download.microsoft.com/download/vb40ent/sample27/1/w9xnt4/en-us/vb4run.exe",
    "sha1": "83e968063272e97bfffd628a73bf0ff5f8e1023b",
    "sha256": "40931308b5a137f9ce3e9da9b43f4ca6688e18b523687cfea8be6cdffa3153fb"
  },
  {
    "url": "https://download.microsoft.com/download/vb50pro/utility/1/win98/en-us/msvbvm50.exe",
    "sha1": "28bfaf09b8ac32cf5ffa81252f3e2fadcb3a8f27",
    "sha256": "b5f8ea5b9d8b30822a2be2cdcb89cda99ec0149832659ad81f45360daa6e6965"
  },
  {
    "url": "https://download.microsoft.com/download/5/a/d/5ad868a0-8ecd-4bb0-a882-fe53eb7ef348/VB6.0-KB290887-X86.exe",
    "sha1": "73ef177008005675134d2f02c6f580515ab0d842",
    "sha256": "467b5a10c369865f2021d379fc0933cb382146b702bbca4bcb703fc86f4322bb"
  },
  {
    "url": "https://download.microsoft.com/download/1/9/f/19fe4660-5792-4683-99e0-8d48c22eed74/Vs6sp6.exe",
    "sha1": "2292437a8967349261c810ae8b456592eeb76620",
    "sha256": "7fa1d1778824b55a5fceb02f45c399b5d4e4dce7403661e67e587b5f455edbf3"
  },
  {
    "url": "https://sourceforge.net/projects/bzflag/files/bzedit%20win32/1.6.5/BZEditW32_1.6.5.exe",
    "sha1": "bdd1b32c4202fd77e6513fd507c8236888b09121",
    "sha256": "84d1bda5dbf814742898a2e1c0e4bc793e9bc1fba4b7a93d59a7ef12bd0fd802"
  },
  {
    "url": "https://download.microsoft.com/download/8/B/4/8B42259F-5D70-43F4-AC2E-4B208FD8D66A/vcredist_x86.EXE",
    "sha1": "b8fab0bb7f62a24ddfe77b19cd9a1451abd7b847",
    "sha256": "4ee4da0fe62d5fa1b5e80c6e6d88a4a2f8b3b140c35da51053d0d7b72a381d29"
  },
  {
    "url": "https://download.microsoft.com/download/5/D/8/5D8C65CB-C849-4025-8E95-C3966CAFD8AE/vcredist_x86.exe",
    "sha1": "470640aa4bb7db8e69196b5edb0010933569e98d",
    "sha256": "6b3e4c51c6c0e5f68c8a72b497445af3dbf976394cbb62aa23569065c28deeb6"
  },
  {
    "url": "https://download.microsoft.com/download/5/D/8/5D8C65CB-C849-4025-8E95-C3966CAFD8AE/vcredist_x64.exe",
    "sha1": "a7c83077b8a28d409e36316d2d7321fa0ccdb7e8",
    "sha256": "b811f2c047a3e828517c234bd4aa4883e1ec591d88fad21289ae68a6915a6665"
  },
  {
    "url": "https://download.microsoft.com/download/5/B/C/5BC5DBB3-652D-4DCE-B14A-475AB85EEF6E/vcredist_x86.exe",
    "sha1": "372d9c1670343d3fb252209ba210d4dc4d67d358",
    "sha256": "8162b2d665ca52884507ede19549e99939ce4ea4a638c537fa653539819138c8"
  },
  {
    "url": "https://download.microsoft.com/download/A/8/0/A80747C3-41BD-45DF-B505-E9710D2744E0/vcredist_x64.exe",
    "sha1": "027d0c2749ec5eb21b031f46aee14c905206f482",
    "sha256": "c6cd2d3f0b11dc2a604ffdc4dd97861a83b77e21709ba71b962a47759c93f4c8"
  },
  {
    "url": "https://download.microsoft.com/download/1/6/B/16B06F60-3B20-4FF2-B699-5E9B7962F9AE/VSU_4/vcredist_x86.exe",
    "sha1": "96b377a27ac5445328cbaae210fc4f0aaa750d3f",
    "sha256": "b924ad8062eaf4e70437c8be50fa612162795ff0839479546ce907ffa8d6e386"
  },
  {
    "url": "https://download.microsoft.com/download/1/6/B/16B06F60-3B20-4FF2-B699-5E9B7962F9AE/VSU_4/vcredist_x64.exe",
    "sha1": "1a5d93dddbc431ab27b1da711cd3370891542797",
    "sha256": "681be3e5ba9fd3da02c09d7e565adfa078640ed66a0d58583efad2c1e3cc4064"
  },
  {
    "url": "https://download.microsoft.com/download/2/E/6/2E61CFA4-993B-4DD4-91DA-3737CD5CD6E3/vcredist_x86.exe",
    "sha1": "df7f0a73bfa077e483e51bfb97f5e2eceedfb6a3",
    "sha256": "a22895e55b26202eae166838edbe2ea6aad00d7ea600c11f8a31ede5cbce2048"
  },
  {
    "url": "https://download.microsoft.com/download/2/E/6/2E61CFA4-993B-4DD4-91DA-3737CD5CD6E3/vcredist_x64.exe",
    "sha1": "8bf41ba9eef02d30635a10433817dbb6886da5a2",
    "sha256": "e554425243e3e8ca1cd5fe550db41e6fa58a007c74fad400274b128452f38fb8"
  },
  {
    "url": "https://download.microsoft.com/download/9/3/F/93FCF1E7-E6A4-478B-96E7-D4B285925B00/vc_redist.x86.exe",
    "sha1": "bfb74e498c44d3a103ca3aa2831763fb417134d1",
    "sha256": "fdd1e1f0dcae2d0aa0720895eff33b927d13076e64464bb7c7e5843b7667cd14"
  },
  {
    "url": "https://download.microsoft.com/download/9/3/F/93FCF1E7-E6A4-478B-96E7-D4B285925B00/vc_redist.x64.exe",
    "sha1": "3155cb0f146b927fcc30647c1a904cd162548c8c",
    "sha256": "5eea714e1f22f1875c1cb7b1738b0c0b1f02aec5ecb95f0fdb1c5171c6cd93a3"
  },
  {
    "url": "https://download.microsoft.com/download/9/2/3/92338cd0-759f-4815-8981-24b437be74ef/vjredist.exe",
    "sha1": "80a098e36b90d159da915aebfbfbacf35f302bd8",
    "sha256": "cf8f3dd4ad41453a302870b74de1c6489e7ed255ad3f652ce4af0b424a933b41"
  },
  {
    "url": "https://download.microsoft.com/download/f/f/1/ff178bb1-da91-48ed-89e5-478a99387d4f/wic_x86_enu.exe",
    "sha1": "53c18652ac2f8a51303deb48a1b7abbdb1db427f",
    "sha256": "196868b09d87ae04e4ab42b4a3e0abbb160500e8ff13deb38e2956ee854868b1"
  },
  {
    "url": "https://download.microsoft.com/download/6/4/5/645FED5F-A6E7-44D9-9D10-FE83348796B0/wic_x64_enu.exe",
    "sha1": "4bdbf76a7bc96453306c893b4a7b2b8ae6127f67",
    "sha256": "5822fecd69a90c2833965a25e8779000825d69cc8c9250933f0ab70df52171e1"
  },
  {
    "url": "https://download.microsoft.com/download/2/8/D/28DA9C3E-6DA2-456F-BD33-1F937EB6E0FF/WindowsServer2003-WindowsMedia-KB2845142-x86-ENU.exe",
    "sha1": "0ace94c09bfab15410db3a15ffa42370891266de",
    "sha256": "51e11691339c1c817b12f92e613145ffcd7b6f7e869d994cc8dbc4591b24f155"
  },
  {
    "url": "https://download.microsoft.com/download/b/c/3/bc3a0c36-fada-497d-a3de-8b0139766f3b/Windows2000-KB917344-56-x86-enu.exe",
    "sha1": "add5f74c5bd4da6cfae47f8306de213ec6ed52c8",
    "sha256": "d6d6c2ac2d2a095b0f0650a9a2e81e8943579699662b5cdbf872649038788c51"
  },
  {
    "url": "https://download.microsoft.com/download/4/4/d/44de8a9e-630d-4c10-9f17-b9b34d3f6417/scripten.exe",
    "sha1": "b15c6a834b7029e2dfed22127cf905b06857e6f5",
    "sha256": "63c781b9e50bfd55f10700eb70b5c571a9bedfd8d35af29f6a22a77550df5e7b"
  },
  {
    "url": "https://download.microsoft.com/download/5/9/1/5912526C-B950-4662-99B6-119A83E60E5C/xnafx31_redist.msi",
    "sha1": "bdd33b677c9576a63ff2a6f65e12c0563cc116e6",
    "sha256": "187e7e6b08fe35428d945612a7d258bfed25fad53cc54882983abdc73fe60f91"
  },
  {
    "url": "https://download.microsoft.com/download/A/C/2/AC2C903B-E6E8-42C2-9FD7-BEBAC362A930/xnafx40_redist.msi",
    "sha1": "49efdc29f65fc8263c196338552c7009fc96c5de",
    "sha256": "e6c41d692ebcba854dad4b1c52bb7ddd05926bad3105595d6596b8bab01c25e7"
  },
  {
    "url": "https://download.microsoft.com/download/E/6/7/E675FFFC-2A6D-4AB0-B3EB-27C9F8C8F696/PowerPointViewer.exe",
    "sha1": "ab48a8ebac88219c84f293c6c1e81f1a0f420da6",
    "sha256": "249473568eba7a1e4f95498acba594e0f42e6581add4dead70c1dfb908a09423"
  },
  {
    "url": "https://download.microsoft.com/download/a/1/8/a180e21e-9c2b-4b54-9c32-bf7fd7429970/EUupdate.EXE",
    "sha1": "9b076c40cb63aa0d8512aa8e610ba11d3466e441",
    "sha256": "464dd2cd5f09f489f9ac86ea7790b7b8548fc4e46d9f889b68d2cdce47e09ea8"
  },
  {
    "url": "https://launchpad.net/takao-fonts/trunk/003.02.01/+download/takao-fonts-ttf-003.02.01.zip",
    "sha1": "4f636d5c7c1bc16b96ea723adb16838cfb6df059",
    "sha256": "2f526a16c7931958f560697d494d8304949b3ce0aef246fb0c727fbbcc39089e"
  },
  {
    "url": "https://www.abisource.com/downloads/abiword/2.8.6/Windows/abiword-setup-2.8.6.exe",
    "sha1": "a91acd3f60e842d23556032d34f1600602768318",
    "sha256": "f85c7f32044bbb4d31f1672c86951e35319f8e89fbd6c01ab4c19e960efd9ff8"
  },
  {
    "url": "https://kb2.adobe.com/cps/403/kb403051/attachments/setup.exe",
    "sha1": "4c79685408fa6ca12ef8bb0e0eaa4a846e21f915",
    "sha256": "4ebe0fcefbe68900ca6bf499432030c9f8eb8828f8cb5a7e1fd1a16c0eba918e"
  },
  {
    "url": "https://www.autohotkey.com/download/AutoHotkey104805_Install.exe",
    "sha1": "13e5a9ca6d5b7705f1cd02560c3af4d38b1904fc",
    "sha256": "4311c3e7c29ed2d67f415138360210bc2f55ff78758b20b003b91d775ee207b9"
  },
  {
    "url": "https://www.cmake.org/files/v2.8/cmake-2.8.11.2-win32-x86.exe",
    "sha1": "d79af5715c0ad48d78bb731cce93b5ad89b16512",
    "sha256": "cb6a7df8fd6f2eca66512279991f3c2349e3f788477c3be8eaa362d46c21dbf0"
  },
  {
    "url": "https://download.microsoft.com/download/whistler/hwdev1/1.0/wxp/en-us/ColorProfile.exe",
    "sha1": "6b72836b32b343c82d0760dff5cb51c2f47170eb",
    "sha256": "d04ac910acdd97abd663f559bebc6440d8d68664bf977ec586035247d7b0f728"
  },
  {
    "url": "https://download.microsoft.com/download/activexcontrolpad/install/4.0.0.950/win98mexp/en-us/setuppad.exe",
    "sha1": "8921e0f52507ca6a373c94d222777c750fb48af7",
    "sha256": "eab94091ac391f9bbc8e355a1d231e6a08b8dbbb0f6539245b7f0c58d94f420c"
  },
  {
    "url": "https://ftp.gnu.org/gnu/gnuzilla/31.7.0/icecat-31.7.0.en-US.win32.zip",
    "sha1": "cf52a728c1af29065b7dc7bdddc9265a79eb5328",
    "sha256": "27d10e63ab9ea4e6995c235b92258b379f79433a06a12e4ad16811801cf81e36"
  },
  {
    "url": "https://github.com/Winetricks/winetricks/raw/master/files/winetest.cat",
    "sha1": "ac8f50dd54d011f3bb1dd79240dae9378748449f",
    "sha256": "5d18ab44fc289100ccf4b51cf614cc2d36f7ca053e557e2ba973811293c97d38"
  },
  {
    "url": "https://download.microsoft.com/download/3/8/8/38889DC1-848C-4BF2-8335-86C573AD86D9/IE7-WindowsXP-x86-enu.exe",
    "sha1": "d39b89c360fbaa9706b5181ae4718100687a5326",
    "sha256": "bf5c325bbe3f4174869b2a8ff75f92833e7f7debe64777ed0faf293c7725cbef"
  },
  {
    "url": "https://github.com/Winetricks/winetricks/raw/master/files/winetest.cat",
    "sha1": "ac8f50dd54d011f3bb1dd79240dae9378748449f",
    "sha256": "5d18ab44fc289100ccf4b51cf614cc2d36f7ca053e557e2ba973811293c97d38"
  },
  {
    "url": "https://download.microsoft.com/download/C/C/0/CC0BD555-33DD-411E-936B-73AC6F95AE11/IE8-WindowsXP-x86-ENU.exe",
    "sha1": "e489483e5001f95da04e1ebf3c664173baef3e26",
    "sha256": "5a2c6c82774bfe99b175f50a05b05bcd1fac7e9d0e54db2534049209f50cd6ef"
  },
  {
    "url": "https://notepad-plus-plus.org/repository/6.x/6.7.9.2/npp.6.7.9.2.Installer.exe",
    "sha1": "34574fb2e4e06ff941061bf444b57ce926ce23d7",
    "sha256": "cecc981d56d759233b804fa77e70ed62e411aaee58dcb1e53b91909c99d29096"
  },
  {
    "url": "https://dl.google.com/picasa/picasa39-setup.exe",
    "sha1": "b3f7e2ee168811cb1d924eb34afe2b0d8153f89f",
    "sha256": "482c1a547d8d3aa25ee446d30ea986de63ef8c8d68b8d1109dd3d9b714e73e08"
  },
  {
    "url": "https://download.microsoft.com/download/7/A/B/7ABD2203-C472-4036-8BA0-E505528CCCB7/winsdk_web.exe",
    "sha1": "a01dcc67a38f461e80ea649edf1353f306582507",
    "sha256": "bb0e3b5d8feb750b3164b657a046f76ff086887719e418f57ce88ada5e8990d5"
  },
  {
    "url": "https://download.microsoft.com/download/A/6/A/A6AC035D-DA3F-4F0C-ADA4-37C8E5D34E3D/winsdk_web.exe",
    "sha1": "a8717ebb20a69c7efa85232bcb9899b8b07f98cf",
    "sha256": "9ea8d82a66a33946e8673df92d784971b35b8f65ade3e0325855be8490e3d51d"
  },
  {
    "url": "https://www.python.org/ftp/python/2.6.2/python-2.6.2.msi",
    "sha1": "2d1503b0e8b7e4c72a276d4d9027cf4856b208b8",
    "sha256": "c2276b398864b822c25a7c240cb12ddb178962afd2e12d602f1a961e31ad52ff"
  },
  {
    "url": "https://download.microsoft.com/download/A/9/1/A91D6B2B-A798-47DF-9C7E-A97854B7DD18/VC.iso",
    "sha1": "1ae44e4eaf8c61c3a39e573fd6efd9889e940529",
    "sha256": "5ae700d0285d94ec6df23828c7dc9f5634cd250363bed72e486916af22ff9545"
  },
  {
    "url": "https://download.microsoft.com/download/7/7/3/7737290f-98e8-45bf-9075-85cc6ae34bf1/VS80sp1-KB926748-X86-INTL.exe",
    "sha1": "8b9a0172efad64774aa122f29e093ad2043b308d",
    "sha256": "a959d1ea52674b5338473be32a1370f9ec80df84629a2ed3471aa911b42d9e50"
  },
  {
    "url": "https://download.microsoft.com/download/8/B/5/8B5804AD-4990-40D0-A6AA-CE894CBBB3DC/VS2008ExpressENUX1397868.iso",
    "sha1": "76c6d28274a67741da720744026ea991a70867d1",
    "sha256": "c4589e21868331b7f8b126220135c88065fecae7cdc94e1a3ff415cb6c813669"
  },
  {
    "url": "https://download.microsoft.com/download/1/b/c/1bc0b1a3-c839-4b36-8f3c-19847ba09299/MPSetup.exe",
    "sha1": "580536d10657fa3868de2869a3902d31a0de791b",
    "sha256": "678c102847c18a92abf13c3fae404c3473a0770c871a046b45efe623c9938fc0"
  },
  {
    "url": "https://download.microsoft.com/download/1/2/a/12a31f29-2fa9-4f50-b95d-e45ef7013f87/MP10Setup.exe",
    "sha1": "69862273a5d9d97b4a2e5a3bd93898d259e86657",
    "sha256": "c1e71784c530035916aad5b09fa002abfbb7569b75208dd79351f29c6d197e03"
  },
  {
    "url": "https://crayonphysicsdeluxe.s3.amazonaws.com/crayon_release52demo.exe",
    "sha1": "4ffd64c630f69e7cf024ef946c2c64c8c4ce4eac",
    "sha256": "3c221f4c4283d89c180337071b5d3f8b88b68cea0558e6f72abcb34ef954b923"
  },
  {
    "url": "https://www.maxandthemagicmarker.com/maxdemo/max_demo_pc.zip",
    "sha1": "1a79c583ff40e7b2cf05d18a89a806fd6b88a5d1",
    "sha256": "6e2abd0cbd0ad04bfea9663402d7e9f24864d3f1c32df69eebf92dfc469fe6dd"
  },
  {
    "url": "https://dldir1.qq.com/qqfile/qq/QQ8.0/16968/QQ8.0.exe",
    "sha1": "ef92f3863113971c95a79aa75e601893d803826c",
    "sha256": "3af11db606ea9f8358db5c9eb12398da3464de020b7da7cbf3e13662ee33d228"
  },
  {
    "url": "https://dldir1.qq.com/qqfile/QQIntl/QQi_PC/QQIntl2.11.exe",
    "sha1": "030df82390e7962177fcef66fc1a0fd1a3ba4090",
    "sha256": "a08e5d8432ad41745cfe92479a9a0c3328a546c27f05486392ca7b77b1cb02a8"
  }
]
```

**Comment by austin987** [comment]
I'm working on a similar fix, actually (with a single commit for each package)..

**Comment by vszakats** [comment]
That's great news, I'm closing this one then, thank you!

**Comment by austin987** [comment]
@vszakats this is mostly done, I used this script:
https://github.com/Winetricks/winetricks/blob/master/misc/convert_sha1_sha256.sh

I believe everything with a download should be done, aside from manual downloads. There may be some other minor bits left, of course. The stuff with no download remains, I plan to add a w_warn for them.

If you have time, try running your script again, and see if it finds anything I missed. If so, please send a PR (I'd prefer one commit per package).

**Comment by vszakats** [comment]
Created #744 with some items my script found.

**Pull request closed without merging**
