### PR TITLE
crypt32: Install both 32 and 64 bit DLLs

### PR DESCRIPTION
**Pull request by qwertychouskie**
Use win7sp1 instead of winxpsp3, it easily provides both 32 bit and 64 bit DLLs, with the added benefit of likely being newer.

### CODE REVIEW

**Comment by austin987** [comment]
Could you rename the old crypt32 to crypt32_winxp, then add yours? That way if any users depend on the older version, they can continue to use it, if needed (a la gdiplus).

**Comment by qwertychouskie** [comment]
> Could you rename the old crypt32 to crypt32_winxp, then add yours? That way if any users depend on the older version, they can continue to use it, if needed (a la gdiplus).

Will do

**Comment by qwertychouskie** [comment]
Update pushed, ready to merge.

**Comment by austin987** [comment]
Thanks!

**Pull request merged**
